### ISSUE TITLE
[add new primary source]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#101]
form incomplete, does not show "pattern" options

**Comment by tuurma** [comment]
confirm

![image](https://user-images.githubusercontent.com/449468/27175668-ccf132cc-51b7-11e7-8058-4724aa159d3a.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27176554-e61da660-51ba-11e7-82e3-06500ee422f4.png)
