### ISSUE TITLE
input form primary sources deleted

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#102]
See e.g. Mokimos from Gaulanitis...he happens to have no sources after I used the delete button. There is no way to display sources once again

**Comment by tuurma** [comment]
@plutonik-a this is another scenario where having 'add' button placed outside of repeat section is necessary

**Comment by tuurma** [comment]
related #100 #91

**Comment by tuurma** [comment]
will be solved with #100; closing this one
