### ISSUE TITLE
[primary sources] box for bilingual and trilingual inscriptions

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#105]
@michaelzellmann @jsblgpn could you please provide details what would you expect here?

**Comment by michaelzellmann** [comment]
This could simply be one more drop-down menu, perhaps under the current “ref. details,” with only three options in the menu, blank (default), bilingual, trilingual. The title of the field could be “Bi/trilingual"

**Comment by tuurma** [comment]
adjust all the existing records

```xquery
for $i in collection('/db/apps/lgpn-data/data/persons')//tei:bibl[@type='primary']/tei:ref[not(@ana)]
return 
    update insert attribute ana {''} into $i
```

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/28118025-7cad4610-6707-11e7-8db4-d8642c882c16.png)
