### ISSUE TITLE
search places

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#109]
places under the name Laodikeia do not show...instead message in red...loading failed.

**Comment by tuurma** [comment]
I can confirm this happens on the server but cannot reproduce locally. Will investigate and report back. Script supplying results for autocomplete returns error for 

http://admin.exist-db.org:41233/exist/apps/lgpn/modules/places.xq?type=meanings&query=laodike&page_limit=10&page=1&_=1497534447708

but works perfectly fine for 

http://admin.exist-db.org:41233/exist/apps/lgpn/modules/places.xq?type=meanings&query=athe&page_limit=10&page=1&_=1497534447708
```
HTTP ERROR 500

Problem accessing /exist/apps/lgpn/modules/places.xq. Reason:

    Server Error
Caused by:

javax.servlet.ServletException: An error occurred: null
	at org.exist.http.servlets.EXistServlet.doGet(EXistServlet.java:263)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
```

**Comment by tuurma** [comment]
The place record for Laodikeia (Lattaquié) had erroneously same values for @ref and @xml:id, thus resulting in never ending loop trying to retrieve regions. Deleted the @ref

```xml
    <place ref="P6ae93e8e-ee03-4317-8d45-cbd1e890329c" type="settlement" xml:id="P6ae93e8e-ee03-4317-8d45-cbd1e890329c">
```

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27192729-48e7efce-51f4-11e7-81d0-336fa422676c.png)
