### ISSUE TITLE
input form - places - search

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#110]
the search diplays both the name and its minor variants as main place name. E.g. Rafid and Al Rafeed (minor variant). Al Rafeed should not appear in the scroll down list of places.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27588288-9bcdad56-5b3f-11e7-8bc9-e15fc02dce9c.png)

**Comment by tuurma** [comment]
there was an inconsistency in attribute values for minor variants, fixed with 
```xquery
for $i in collection('/db/apps/lgpn-data/data/places')//tei:placeName[@subtype='variant']
return
    update replace $i/@subtype  with 'minor'
```

**Comment by tuurma** [comment]
after fix

![image](https://user-images.githubusercontent.com/449468/27589293-d9c30482-5b42-11e7-9b11-737ff377e01e.png)

**Comment by JSBLGPN** [comment]
Al Rafeed is the alternative name (minor variant) and it should not appear in the scroll down list. Rafid should appear instead.
Thanks

**Comment by tuurma** [comment]
thanks, just noticed I have the condition wrong way around, now fixed :-)

![image](https://user-images.githubusercontent.com/449468/27589868-ca8fced0-5b44-11e7-9b6a-89e8d91ad8e4.png)
