### ISSUE TITLE
primary sources, box: linking

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#113]
no box linking (with options = and +) for entries created before the addition of this box. Please add this field for old entries. Thanks.
E.g.: Zenon and Esatiaia from Sidon, with reference Syria 27 (1950) p. 250 no. 13.

**Comment by tuurma** [comment]
```xquery
xquery version "3.0";

declare namespace tei="http://www.tei-c.org/ns/1.0";

for $i in collection('/db/apps/lgpn-data/data/persons')//tei:bibl[@type='primary'][not(@ana)]
return
    update insert attribute ana {''} into $i 
```

**Comment by tuurma** [comment]
http://admin.exist-db.org:41233/exist/apps/lgpn/editor.xhtml?id=Pa333f0a9-3581-4a60-b891-8ddf3dae1706

![image](https://user-images.githubusercontent.com/449468/27550584-267e3446-5a98-11e7-90bd-85ce543348f3.png)
