### ISSUE TITLE
primary sources : box : linking

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#114]
Add please the option  ;= 
On the printed volume this will appear as just =
[The current option = will appear within brackets ( ) on the printed volume].

**Comment by tuurma** [comment]
@JSBLGPN what would be the meaning of this option? looking for a meaningful label to use in the TEI source

so far we have `=` with label `equal`
and `+` with label `correction`

**Comment by JSBLGPN** [comment]
Is the following label ok?
;=    meaning    'published twice'. 
On the printed pages ;= appears as =...

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27550205-b8a97012-5a96-11e7-922c-45a2284324ed.png)
