### ISSUE TITLE
[import] vol 5C places

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#116]

**Comment by tuurma** [comment]
select only places with arid=5, then filter out the ones with placeid already existing in the database

use islid, towid, towdeme, polis to find a parent in places hierarchy

**Comment by tuurma** [comment]
list of all V5 places imported from Ingres with unicode conversions etc http://admin.exist-db.org:41233/exist/apps/lgpn-data/data/auxiliary/references/places-V5C.xml

generated TEI
http://admin.exist-db.org:41233/exist/apps/lgpn/import/places5sanity.xqm

some regions have no place entries, thus nested places get no reference 

```xml
<place xmlns="http://www.tei-c.org/ns/1.0" xml:id="LGPN_53080" type="settlement" ref="">
<placeName type="" subtype="" cert="" xml:lang="">Gölören (mod.)</placeName>
</place>
```

(mod) should be converted into type="modern"
? are silently skipped for the time being

**Comment by tuurma** [comment]
I have added 3 regions to accommodate places from V5

* Asia Minor Pe314d69e-fbd0-4c8b-942f-919a3783e598
  -  Inland Asia Minor P6afbf097-c078-4a08-a98d-f2c71667a366
  - Coastal Asia Minor P2856bfdb-16e1-4b62-bb9c-93098f3bd521

**Comment by tuurma** [comment]
records awaiting import can be viewed at http://admin.exist-db.org:41233/exist/apps/lgpn/import/places5sanity.xqm

**Comment by tuurma** [comment]
There are 28 records marked as 'suspicious' atm at http://admin.exist-db.org:41233/exist/apps/lgpn/import/places5sanity.xqm

I think we can merge these places into the database and adjust manually where necessary.

**Comment by tuurma** [comment]
Record of the import is available at:
https://docs.google.com/spreadsheets/d/1f-NYs5Bky-RdL2dq9ClNnXRzXDuMQuX2507xmy-9Ppk/edit#gid=0

I have merged all the places generated into eXist database, so they should be immediately accessible.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/28159092-bd83c7d4-67b3-11e7-85d8-b34a0f6c0196.png)
