### ISSUE TITLE
Names field : option certainty has disappeared in some entries

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#117]
Example: Soste /Σωστη from Sidon

**Comment by tuurma** [comment]
case discussed: http://admin.exist-db.org:41233/exist/apps/lgpn/editor.xhtml?id=Pea04ac41-5f72-4f84-ad75-1bf7ec36c3ca

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27552783-9183dfae-5aa0-11e7-9151-f6bd2713d878.png)

**Comment by tuurma** [comment]
fixed with

```xquery

xquery version "3.0";

declare namespace tei="http://www.tei-c.org/ns/1.0";

for $i in collection('/db/apps/lgpn-data/data/persons')//tei:nym[@type=''][not(@cert)]
return
    update insert attribute cert {'high'} into $i 
```
