### ISSUE TITLE
[names] hide double input fields

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#118]
xf:input elements bound to the model and thus necessary to display validation alerts but for autocompletes they need to be hidden from view

please change the layout so that xf:input follows the autocomplete (so reverse current situation) and make the xf:input invisible but keep alerts rendered

```xml
        <xf:input ref="@nymRef" class="-custom-alert">
                                                            <xf:action ev:event="nyms_autocomplete-callback">
                                                                <xf:setvalue ref="." value="event('termValue')"/>
                                                            </xf:action>
                                                            <xf:label class="input-group-addon">
                                                                <i class="glyphicon glyphicon-book"/>
                                                            </xf:label>
                                                            <xf:hint>normalized form</xf:hint>
                                                            <xf:alert>blah</xf:alert>
     </xf:input>
     <input type="hidden" class="tp-input" data-function="nyms_autocomplete" placeholder="Type to search name" autocomplete="off"/>

```

![image](https://user-images.githubusercontent.com/449468/27535900-7bb7bc22-5a64-11e7-9321-896988084d83.png)

**Comment by tuurma** [comment]
Styling hiccup still persists: if the field is filled, some artifacts from hidden xf:input remain

![image](https://user-images.githubusercontent.com/449468/27740523-35686818-5daa-11e7-95a8-8a69a4716220.png)

missing name is signaled properly

![image](https://user-images.githubusercontent.com/449468/27740552-54a6abc2-5daa-11e7-844c-9f5e0cb7cf33.png)

**Comment by plutonik-a** [comment]
> Styling hiccup still persists: if the field is filled, some artifacts from hidden xf:input remain

@tuurma 
Strange, that this still appears, because I tested it thoroughly. I will have a look at it and fix it asap.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27822526-c84908a4-609d-11e7-9525-387c95cfe749.png)

Thanks @plutonik-a for your fix!
