### ISSUE TITLE
place field - select an existing place : only one Antiocheia at the moment

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#121]
there should be several places called Antiocheia and in brackets their region. At the moment there is only one Antiocheia (Persis).
Thanks

**Comment by tuurma** [comment]
Thanks, fixed now, I think

![image](https://user-images.githubusercontent.com/449468/27591094-99efe7e8-5b48-11e7-92d1-b73a4f03ef91.png)
