### ISSUE TITLE
field status : box profession : add a profession

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#122]
please add the profession "mechant" in the scroll down list (if possible add it right after the profession "pragmateutes")
Thanks

**Comment by tuurma** [comment]
did you mean `merchant` by any chance?

**Comment by JSBLGPN** [comment]
yes; sorry...thanks

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27629654-f60ee478-5bea-11e7-834b-636fa4ceaeb8.png)
