### ISSUE TITLE
[references]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#130]
Subform to add new references is not working
![failed to save data](https://user-images.githubusercontent.com/20699164/27825629-142a03c2-60a8-11e7-95fd-90c4e1dc9e20.png)

**Comment by tuurma** [comment]
confirmed locally. I'm on it.

**Comment by tuurma** [comment]
@michaelzellmann let me know if any trouble persists, but it should work fine now

**Comment by michaelzellmann** [comment]
Thanks, it is working now
