### ISSUE TITLE
list of person records

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#140]
if you search for people from Gasima (a place), the display of this place name in list of person records is weird for two cases.
thanks

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/28113011-e60e36c4-66f2-11e7-99ce-21d467e9fb46.png)

**Comment by tuurma** [comment]
Corrupted place record (which erroneously included nested place entry for Tall Kurdi)

![image](https://user-images.githubusercontent.com/449468/28114301-2adbdc8e-66f8-11e7-8d83-5c89017232eb.png)

**Comment by tuurma** [comment]
No other records with this nested place pattern, closing

`collection('/db/apps/lgpn-data/data/places')//tei:place[descendant::tei:place]`
