### ISSUE TITLE
certainty

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#141]
for the individual called Ιασης from Sidon (reference SEG XXXII 1483) in name filed box certainty is not available. 
Thanks

**Comment by tuurma** [comment]
http://admin.exist-db.org:41233/exist/apps/lgpn/editor.xhtml?id=P770821e8-ebef-4f28-b50e-629891645890

**Comment by tuurma** [comment]
2112 records are affected

`collection('/db/apps/lgpn-data/data/persons')//tei:nym[not(@cert)][not(@type='Roman')]`

**Comment by tuurma** [comment]
fixed with 

```xquery
for $i in collection('/db/apps/lgpn-data/data/persons')//tei:nym[not(@cert)][not(@type='Roman')]
return 
    update insert attribute cert {'high'} into $i
```
