### ISSUE TITLE
place name : Delos

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#148]
the island of Delos is no longer available in the place names list...

**Comment by tuurma** [comment]
```xml
               <place ref="" subtype="island" type="region" xml:id="LGPN_11270">
                    <placeName cert="" subtype="minor" type="modern" xml:lang="">Delos</placeName>
...
```

for whatever reason, Delos had it's only name entry as a 'minor' variant, thus was not shown on a list. Will check for other occurrences of this pattern.

**Comment by tuurma** [comment]
No other cases for this scenario occur in the database

`collection('/db/apps/lgpn-data/data/places')//tei:place[count(./tei:placeName)=1][tei:placeName/@subtype='minor']`
