### ISSUE TITLE
list of person records - reference

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#156]
display the linking element between 2 sources or more as in the book
> ;= book: =
> = book: ()
> \+ book: &

thanks

**Comment by tuurma** [comment]
### correction /+

![image](https://user-images.githubusercontent.com/449468/28822078-cf0cbd8e-76af-11e7-8944-79a366590caf.png)

### equal =

![image](https://user-images.githubusercontent.com/449468/28822143-1068e028-76b0-11e7-80db-2800c545b8da.png)

**Comment by tuurma** [comment]
355 with linking marker on 1st source
`collection('/db/apps/lgpn-data/data')//tei:bibl[@type='primary'][not(preceding-sibling::tei:bibl[@type='primary'])][@ana ne '']`

332 on second 
`collection('/db/apps/lgpn-data/data')//tei:bibl[@type='primary'][preceding-sibling::tei:bibl[@type='primary']][@ana ne '']`

**Comment by tuurma** [comment]
Handling of = linking 

<img width="984" alt="image" src="https://user-images.githubusercontent.com/449468/62861269-326bfc00-bd03-11e9-86a2-e6a6fd96be9f.png">

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/449468/62861301-49aae980-bd03-11e9-8338-37e6d75403d6.png">
