### ISSUE TITLE
display list of person records

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#162]
Pc13679d6-9ac7-4f1a-96d4-5120ceb11231

for this entry (Philtate from Byblos) the secondary sources does not appear correctly in the list of person records

**Comment by tuurma** [comment]
In the new version looks ok to me, so closing. Please reopen if you notice any problems.

![image](https://user-images.githubusercontent.com/449468/42780980-1e787ef0-8945-11e8-92bb-ee7f659c1149.png)

![image](https://user-images.githubusercontent.com/449468/42781003-2f634a6a-8945-11e8-91b8-e8dc78d5583d.png)
