### ISSUE TITLE
problem with volume box

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#164]
these three people were without volume number, so vol number 6 was added to each of them, but as a result entries were duplicated...could you please fix and delete the three following ones?

P9dda4b06-bf48-4a14-8156-f0d71f7b98f9

P6766b527-4b7b-4fd6-bff3-879302a685be

P25a4f2c9-273c-404c-a36e-9920cc6f5c87

**Comment by JSBLGPN** [comment]
actually don't delete them please because the ones I have just changed failed to load...

P9dda4b06-bf48-4a14-8156-f0d71f7b98f9

P6766b527-4b7b-4fd6-bff3-879302a685be

P25a4f2c9-273c-404c-a36e-9920cc6f5c87

**Comment by tuurma** [comment]
same as #174 so closing as that one has just been solved
