### ISSUE TITLE
display person records

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#165]
See these two entries and the secondary sources don't display in the same way... 

P49e334de-a35a-4e97-a70a-86444412ee1a

P5fb65157-d31c-4ef0-8ec1-23078e24f1f1

**Comment by JSBLGPN** [comment]
related problem for this entry: 
P0a5fece4-9eae-49b4-a8f5-e6aa1800abac

in this case (Hajjar) should come before CRAI. in fact I entered first IWaddington then CRAI, saved and then added later Hajjar...

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/42781301-08167c9c-8946-11e8-900c-c9f9ae0a3598.png)


![image](https://user-images.githubusercontent.com/449468/42781121-88a93904-8945-11e8-9b81-eb5320bb1928.png)

![image](https://user-images.githubusercontent.com/449468/42781079-72763e66-8945-11e8-9023-2c5a7d687b3d.png)

**Comment by tuurma** [comment]
difference is in the linking of the sources: entries with = are shown in parentheses

![image](https://user-images.githubusercontent.com/449468/42781432-6c98ad02-8946-11e8-9082-cc474b00a6cb.png)
