### ISSUE TITLE
Display 'Details' of Secondary Sources

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#170]
Please add the source 'Details' field to the display in the names list for secondary sources just as done currently for primary sources

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/37465151-ae4e3476-285a-11e8-82cf-2ce538a7ef8c.png)

corresponding `tei:bibl[@type='auxiliary']`

```xml
                    <bibl ana="location" subtype="secondary" type="auxiliary">
                        <ref target="SEG"/>
                        <seg type="details">XXXVIII 1657</seg>
                        <ptr ref=""/>
                    </bibl>
```

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/37465499-921a3498-285b-11e8-892d-c3d4346006ad.png)
