### ISSUE TITLE
Add "Age" to [General]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#171]
Add text-string field for "Age" of person at death, can be placed below [NotAfter] field in [General] area

**Comment by tuurma** [comment]
Age will be represented as `<age type="death"/>` element in TEI

```xquery
xquery version "3.1";

declare namespace tei="http://www.tei-c.org/ns/1.0";

let $age:=
    <age xmlns="http://www.tei-c.org/ns/1.0" type="death"/>

for $element in collection("/db/apps/lgpn-data/data/persons")//tei:person[not(tei:age)]

return

    update insert $age following $element/tei:birth
```

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/37156076-5520f886-22e5-11e8-9110-c8d653627654.png)
