### ISSUE TITLE
volumes issue

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#174]
I saved an individual in volume 6. I wanted to change volume and put the individual Other. I can not load the data anymore...
Aristolochos:

http://clas-lgpn4.classics.ox.ac.uk/exist/apps/lgpn/editor.xhtml?id=Pae241dbe-e439-48f3-85f9-20523be01f6d

and Theophilos:

http://clas-lgpn4.classics.ox.ac.uk/exist/apps/lgpn/editor.xhtml?id=Pc2f240f9-f6d0-4058-a08d-1030c61f7597

Thanks.

**Comment by tuurma** [comment]
There are 36 duplicated person records (so 72 entries altogether)

```xquery
for $group in collection($ppl)//tei:person
let $id := $group/@xml:id
group by $id

return 
    if (count($group)>1) 
    then 
          for $p in $group return $p  
   else 
         ()
```

**Comment by tuurma** [comment]
Removed the duplicates with 

```xquery 

let $ppl:='/db/apps/lgpn-data/data/persons'

for $group in collection($ppl)//tei:person
let $id := $group/@xml:id
group by $id

return 
    if (count($group)>1) then 
        for $p in subsequence($group, 2)
        return ('remove ' || util:collection-name($p) || util:document-name($p),
        xmldb:remove(util:collection-name($p), util:document-name($p)))
    else ()
   ```
