### ISSUE TITLE
move lgpn to tei-publisher app blueprint

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#175]
Current LGPN setup is based on the original design by Tobi which was not using tei-publisher as a blueprint yet. We'd like to align with tei-publisher as it will make new milestone of producing print output much easier and should also fix some problems with logins and broken sessions.

Way to go would be to generate a new app from the TEI Publisher and port editor.xhtml together with subforms place.xhtml, bibl.xhtml.

@JoernT would you be happy to advise on this?

**Comment by JoernT** [comment]
as far as i can see the resources all seem to be valid. JS is mostly dealing with autocomplete control. I would generate the app and move all these files over in a first step. Then, just to be sure check against Publisher resources.

A first glance revealed that publisher already has jquery (no problem - just replace) and bootstrap (should be no problem either).

**Comment by plutonik-a** [comment]
@joern @magda   
Please consider that the layout that has been customized especially for the very specific xhtml markup and has to be reworked as well. 

But in the end, it will be much easier to extend or change CSS, once we return to TEI-Publisher templates / layout.

**Comment by tuurma** [comment]
What we decided on with Alexandra today was to move editor styles into separate collection to keep them isolated and make further updates easy

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/40179989-01a55c6e-59e6-11e8-8d54-23307825977e.png)

**Comment by tuurma** [comment]
Current version has been deployed to the testing server at http://admin.existsolutions.com:55221/exist/apps/lgpn-editor/

It is based on the TEI Publisher to conform to best practices and share the code base we at eXist solutions use as a blueprint for TEI projects.

Major changes between old version of LGPN and a new LGPN-editor

1. separation of editing facilities from public-facing website
2. individual user logins
3. browsing based on TEI Publisher listing and pagination code, adjusted for tabular display
4. filtering of records by name, id, volume, place etc in place of single search field
5. ability to delete entries
6. improved performance

![image](https://user-images.githubusercontent.com/449468/40327537-a1639dc8-5d43-11e8-8183-a6305b8dfc0c.png)

**Comment by tuurma** [comment]
> 1. We would like to be able to do searches of partial words without diacritical marks as was possible previously. This is particularly necessary for the personal names and modern Turkish and Arabic toponyms.

I have added a filtering option `Name (exact)` which searches for an exact match and rewired `Name` filter to ignore diacritics.

>  2. We need to be able to search by reference as well as name and place, ideally by more than a single variable simultaneously (e.g. name and place, name and reference)

Not done yet, started to add multiple filtering option (3) and (4) and will follow with additional filters (like reference, period etc)

>   3. Ideally we should like to be able to search by initial letter without generating extraneous material – e.g. search for names beginning Αβδ without listing all names where the αβδ string occurs.

I have added the option to use wildcard `*` for matching partial names, eg. `Ὀλυμ*` (3). Still need to make it work in the initial position to allow queries like `*λυμ`.

>  4. It would be helpful to reinstate the ability to sort the data by the main variables (name, place, date, reference).

Added the sort by box (2), will extend the list of sorting variables offered.

>  5. It is not clear to us how one accesses the entry form from the new interface.

For this logging in first is necessary via button in the top right corner (1). Then clicking on the pencil icon next to the name (5) brings the editor window in the new browser tab.
Please use the user and password provided in my email from last week. I will supply individual logins as we deploy the test version to Oxford server.
 
![image](https://user-images.githubusercontent.com/449468/40679617-f3c9e75c-6383-11e8-8969-6a4518b25311.png)

**Comment by tuurma** [comment]
I have deployed the new version at http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor, the old one is still running and can be used but will not be further maintained and after receiving approval from the team it will be switched off.

![image](https://user-images.githubusercontent.com/449468/42776504-8232c878-8937-11e8-9d0e-018c2fe21466.png)
