### ISSUE TITLE
Search sources of less than 3 characters

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#176]
some sources have less than 3 characters and are not searchable at the moment
Ex. D. = Demosthenes

**Comment by tuurma** [comment]
added the option to search inside full reference, the side effect is that sometimes more results are found

![image](https://user-images.githubusercontent.com/449468/41112809-3902db14-6a80-11e8-9b51-cd4310c99a79.png)

Hope this approach is ok? Please reopen if you'd like me to change the behaviour.
