### ISSUE TITLE
Relationships ; search relative

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#177]
the drop list cannot distinguish between individuals referenced by secondary sources only... Example search for the name Akakios and several appear with no references afterwards, but just a blank...

**Comment by tuurma** [comment]
Added displaying secondary source where there's no primary one
It doesn't entirely solve the problem as there still may be entries that look exactly the same

![image](https://user-images.githubusercontent.com/449468/41111951-c9a53a70-6a7d-11e8-976d-0457f11accb1.png)

When finding an entry in the dropdown is problematic, it is possible to copy person's id from the list 

![image](https://user-images.githubusercontent.com/449468/41112138-6bae8d44-6a7e-11e8-9632-31a5091511ca.png)

and then just paste into Search Relative dropdown

![image](https://user-images.githubusercontent.com/449468/41112194-9c9e7f9a-6a7e-11e8-8409-50321928cb11.png)

**Comment by tuurma** [comment]
Please note that in new version copying the id to clipboard looks slightly different (fingerprint icon)

![image](https://user-images.githubusercontent.com/449468/41112320-e5c1d3ca-6a7e-11e8-8142-8a85b8e5c2ec.png)

**Comment by JSBLGPN** [comment]
Cases such as Akakios PLRE or Akakios RE are all followed by more specifications in the database: ex. Akakios PLRE III (3) or Akakios RE (1). Is it possible to display a more complete reference in the dropdown?

**Comment by tuurma** [comment]
Looked more closely, and there were further details about a person in the dropdown that were no longer showing due to a bug which I now fixed

![image](https://user-images.githubusercontent.com/449468/41593902-df7e7922-73c1-11e8-82cb-fcafe25b4218.png)
