### ISSUE TITLE
Place names search and autocomplete

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#179]
Could the autocomplete and search functions for place names be made insensitive to special characters? E.g., a search for Salkhad should turn up also Ṣalkhad, or Jabir also Jābir.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/41429232-c7ce7178-700c-11e8-8937-c26eea926730.png)

vs

![image](https://user-images.githubusercontent.com/449468/41429256-d7737984-700c-11e8-81ea-eabeee05a026.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/41429586-c95c00c2-700d-11e8-885a-dff5bafb31bd.png)
