### ISSUE TITLE
place names: a list by region

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#180]
Is it possible to extract all the place names registered under Syria? We now need to tidy up this list and fix the borders between cities within Syria
Thanks

**Comment by tuurma** [comment]
Please check http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/placeList.xql

By default it shows places in Syria, but you can query for any other place by its id, appending `?place=Place-Id` at the end, eg for Antioch

http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/placeList.xql?place=LGPN_70050

NB It's not terribly fast, taking about 30s to produce the full list for Syria

Places are numbered reflecting parent place, so for a place 4th in a sequence, nested locations get 4.1, 4.2 etc

![image](https://user-images.githubusercontent.com/449468/41377324-06b12dc4-6f5c-11e8-94fc-a631f0d7fb95.png)
