### ISSUE TITLE
integrate place list into LGPN system

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#181]
Can we produce this kind of list ourselves?

**Comment by JSBLGPN** [comment]
1. Can we sort this list? Can we search this list?

2. Are we able to know how many individuals are recorded under each place name?  

3. How do we deal with duplicate place names (Apameia in Syria and Apameia-Pella in Syria: this is the same place)? 

4. Many of theses places will not appear in the book (e.g. Kesch 'Al) and the individuals will be recorded under the next bigger place name with the indication 'territory' in the book (in the case of Kesch Al: Antioch [territ.]). How can we automate this change so that some place names appear only as territory of a bigger place.
Thanks a lot

**Comment by tuurma** [comment]
continuation of #180

**Comment by tuurma** [comment]
continuation of #180

**Comment by tuurma** [comment]
Thanks Jean-Sebastien for your remarks which illustrate better what you need the list for. I will try to integrate the list properly into LGPN system, so it shows more information and allows for sorting and searching.

As for 3 and 4 I will open separate issues for these, just let me think how best to solve them.

**Comment by JSBLGPN** [comment]
In the catalogue of place names we need to be able to see which places are nested in larger places. 
There is a system of nested places in the online LGPN search database: http://clas-lgpn2.classics.ox.ac.uk/

**Comment by JSBLGPN** [comment]
For example, the city of Nikopolis (modern Islaye) will go in the region of Kommagene. It has been authorised in 3 different ways:
Nikopolis (Syria)
Nikopolis (Kommagene)
Nicopolis (Commagene)

It is possible that some places are nested in these three places and we need to be able to find them and harmonise everything to Nikopolis (Kommagene)

**Comment by tuurma** [comment]
Adjusted current list of places, so it displays not just a place name but also name of the region and allows to move to a place region. In the next step, I'll add list of nested places

NB not deployed on the server yet.

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/449468/47813697-1850c680-dd4c-11e8-956e-1b310c2f41e7.png">

**Comment by tuurma** [comment]
Linked up alphabetical list of place names

NB not deployed yet

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/449468/47816431-7634dc80-dd53-11e8-8cca-74297ea6c707.png">

**Comment by tuurma** [comment]
screenshot of nested places (planning to deploy on the server tonight)

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/449468/48483582-1ee34180-e814-11e8-8445-ca34a45a4e17.png">

**Comment by tuurma** [comment]
deployed on the server now

<img width="590" alt="image" src="https://user-images.githubusercontent.com/449468/48510244-8967a200-e853-11e8-9954-e32fb3f30344.png">

**Comment by JSBLGPN** [comment]
1). Numbers of people do not match. There are more people for Persia and Armenia in the database.
2). We would need to produce pdfs of these lists (place and weights).
3). Ideally we would need to be able to click on the place and edit the place (change the spelling, for example)
4). For the list of names in alphabetical order: 
4.1. the first is blank (problem) and the last one is misplaced.
4.2. For Arabic place names beginning with a vowel + a diacritic mark (nos 2-18; 27; 348; 479-483), the diacritic mark should be disregarded. Example: no. 2 comes between 20 and 21.

**Comment by JSBLGPN** [comment]
There is still the question of what to do with the place names that will not appear in the book.

**Comment by tuurma** [comment]
For place names not to appear in the book, I'd think we need a marker on that place to say it needs to be aggregated under broader territory. One question, would it always be the place directly over in the hierarchy, or would there sometimes even be a whole nested structure of places to be disregarded.

eg.

Place A
    nested area A-1
         sub-nested area A-1-1

where both A-1-1 and A-1 would need to be grouped under A?

**Comment by JSBLGPN** [comment]
I think that for people numbers we should aim at this

![image](https://user-images.githubusercontent.com/18262359/48772893-a968ec80-ecbd-11e8-9015-873efae239a7.png)

**Comment by tuurma** [comment]
> 1). Numbers of people do not match. There are more people for Persia and Armenia in the database.

I have filtered out relations where people are not citizens of that place (understood this is what you need). Could this be why numbers don't match?

> 2). We would need to produce pdfs of these lists (place and weights).

Understood

> 3). Ideally we would need to be able to click on the place and edit the place (change the spelling, for example)

Agree, working on incorporating it.

> 4). For the list of names in alphabetical order:
> 4.1. the first is blank (problem) and the last one is misplaced.
> 4.2. For Arabic place names beginning with a vowel + a diacritic mark (nos 2-18; 27; 348; 479-483), > the diacritic mark should be disregarded. Example: no. 2 comes between 20 and 21.

Bit more complicated to implement custom ordering, but certainly doable, will keep you posted on progress.

**Comment by JSBLGPN** [comment]
1). I think that your solution could work for some (and I think many) places (like villages) and they would fall under the next above place. I don't think that a whole nested structure of places would be disregarded.

2). But there is also this kind of case: a man from Tyre attested in Bosra (Arabia, volum 6): 
In the database he is recorded with two places: his city : Tyre; his attested place: Bosra. So Bosra is sometimes in and sometimes out of the book.

**Comment by tuurma** [comment]
> 2). But there is also this kind of case: a man from Tyre attested in Bosra (Arabia, volum 6):
In the database he is recorded with two places: his city : Tyre; his attested place: Bosra. So Bosra is sometimes in and sometimes out of the book.

Does this mean that Bosra would otherwise fall under it's 'parent' place? Or just that a man from Tyre would normally fall under different volume?

**Comment by JSBLGPN** [comment]
Sorry I was not clear: both Tyre and Bosra appear in volume 6 otherwise, but for our man from Tyre attested in Bosra he will appear in the book only under his place of origin (Tyre). If the attested place is the only known place, the attested place is used in the book followed by an asterix.

**Comment by tuurma** [comment]
Yes, I remember you have explained to me the general rules on treatment of attested, uncertain etc places, so I see no conflict with folding places under their parent location. I will prepare a mockup to illustrate this for Kesch Al place you mentioned.

**Comment by JSBLGPN** [comment]
I am not sure I understand the solution you suggest but if a man is from Bosra, he appears under Bosra in the book. So Bosra as a place of origin goes in the book, but Bosra as an attested place only goes in the book if there is no other known place.
Thanks

**Comment by tuurma** [comment]
Yes, I understand.

**Comment by JSBLGPN** [comment]
> > 1). Numbers of people do not match. There are more people for Persia and Armenia in the database.
> 
> I have filtered out relations where people are not citizens of that place (understood this is what you need). Could this be why numbers don't match?
> 
Yes this is likely the origin of the problem. We would need every one to appear in the list.
In the book, all the people will be assigned to their first place name:
-- "citizen" and "ethnic" will appear under the assigned place name, 
-- "attested at" will appear under the assigned place name followed by an *

(there will be also resident and alternative origin going to the final brackets)

Thanks,
JS

**Comment by JSBLGPN** [comment]
Also when we click on the number of people next to a place, like Caria (region), Antiocheia (79)...we get to a list of 126 entries...so 79 and 126 don't match. Sometimes for Commagene (region), Germanikeia Kaisaereia (26)...when we click, we get to a blank list...

**Comment by JSBLGPN** [comment]
We have Commagene and Kommagene. Nicopolis was nested in Commagene and I have corrected the place form, and changed it for Nicopolis (Kommagene). But in the list of place names, this hasn't been upgraded. Nicopolis still appears under Commagene...I thought this would work...

**Comment by tuurma** [comment]
Now all places referred to in a volume are listed in the Proofing tab, so numbers should match between list of places and searching in persons. I've added an edit link to directly edit place record from place list.

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/449468/49396853-6f2a3100-f73a-11e8-83d7-a4d93b3b04f6.png">

Places which should be only grouped under their parent place should have a field checked in the place editor 

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/449468/49399226-06928280-f741-11e8-9696-8f0403fe0ad9.png">

and as a result they will be dimmed in the list of places

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/449468/49399287-304ba980-f741-11e8-801b-3c04ae0a2a87.png">

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/449468/49397338-8584bc80-f73b-11e8-92cd-aacba03f63ea.png">

and people listed under that name will also be counted in the (territory) column for the parent place

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/449468/49399143-c7fcc800-f740-11e8-85d2-78e3e359cc81.png">

**Comment by tuurma** [comment]
since remaining question is about duplicate places and it has its own issue in #211 I will close this one
