### ISSUE TITLE
search place names with diacritic marks: urgent

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#182]
in the list of person records we cannot search for place names with diacritic marks: eg. Dūma. search for Duma or Dūma, return nothing. So we cannot retrieve the material from this place and others and therefore there is a risk to encode material twice. so it is kind of urgent.
Thanks

**Comment by tuurma** [comment]
thanks, I'm on it

**Comment by tuurma** [comment]
fix for exact match

![image](https://user-images.githubusercontent.com/449468/41931777-5ab5cd8a-797f-11e8-9e93-37a40889debc.png)

**Comment by tuurma** [comment]
diacritic insensitive

![image](https://user-images.githubusercontent.com/449468/41931901-bf108c02-797f-11e8-9d4f-c03b527d4c84.png)
