### ISSUE TITLE
display references

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#183]
P0a5fece4-9eae-49b4-a8f5-e6aa1800abac

there is still a problem with the display of this entry in the list of person records: 
it should not appear like this
Waddington_ISyrie 2556, 3; CRAI 1900 p. 155; (Hajjar 167)

but it should appear like this:
Waddington_ISyrie 2556, 3; (Hajjar 167); CRAI 1900 p. 155

the entry has been correctly entered

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/43972401-85f6f51e-9cd4-11e8-9f20-ae1250f48b32.png)
