### ISSUE TITLE
New list of person records - important

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#184]
When we correct an old entry, the entry does not show in the new list of person records
Example: the name Χοριανης. 

When we create a new entry, it shows in the list of person records. Example: Φαρνουχος

**Comment by tuurma** [comment]
It was due to old editor not triggering an update of metadata indexes used by search function. Since now even old application links to the new editor, this issue should not reappear. I have triggered global metadata index update to make sure all entries are up to date.
