### ISSUE TITLE
new list of person records: search by reference

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#186]
If we look for a reference with an exact number: example IMnBeyrouth 337, the search returns all the numbers for IMnBeurouth...in the old version...this search returns only IMnBeyrouth 337. Can we keep the old version way of searching?

**Comment by JSBLGPN** [comment]
another problem with the search reference in the new editor is that we need to know the exact reference:
so if I just search for Balty, the search returns nothing. I need to search for Balty_Guide_Apamée ...it seems to me better with the old list of person records with which we search references by bits.

**Comment by tuurma** [comment]
to find matches starting with query string one needs to add a trailing wildcard so search for `Balty*`, for the exact page number example one could wrap the search in quotes, so `"IMnBeyrouth 337"` , fuller discussion in #208
