### ISSUE TITLE
New professions, new tribes

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#187]
Could you write a small summary of how to add new professions?

**Comment by tuurma** [comment]
When logged in, go to Admin menu > Edit professions. It will open a new browser tab with eXide editor open with the file that stores professions

<img width="1672" alt="screen shot 2018-08-10 at 19 45 19" src="https://user-images.githubusercontent.com/449468/43973742-a6e62fde-9cd8-11e8-9e8e-0ccb67268941.png">

You may need to log in again in eXide (check if it shows you are logged in as lgpn at the top (cf screenshot below))

You may add new entries in the form

```xml
    <category xml:id="coin_engraver">
        <catDesc xml:lang="en">coin engraver</catDesc>
    </category>
```

NB that xml:id may not contain spaces, / or other special characters. It is only an internal id and users will only see the label from catDesc element.

After using a profession in person records you MUST NOT change its xml:id or database will no longer be able to link the person record with a profession. You may change the label in catDesc freely at any time.

When you're done introducing changes make sure that no errors are reported at the bottom of eXide screen and click Save button.

<img width="847" alt="screen shot 2018-08-10 at 19 49 45" src="https://user-images.githubusercontent.com/449468/43973808-ce99bbfe-9cd8-11e8-8b9f-385ca24c6819.png">


<img width="1474" alt="screen shot 2018-08-10 at 19 56 31" src="https://user-images.githubusercontent.com/449468/43973790-c2dfc59c-9cd8-11e8-88b5-c90329846e0b.png">

**Comment by tuurma** [comment]
Could you please give me a list of other lists you might want to adjust so I can add relevant entries to the Admin menu?

**Comment by JSBLGPN** [comment]
- source
- status (+subcategory)
- religion (+subcategory)
- roman world (+subcategory)
- office (+subcategory)

thanks

**Comment by tuurma** [comment]
To avoid mixing up different kinds of administrative operations I am adding a new menu position called Taxonomies to hold all the links

![image](https://user-images.githubusercontent.com/449468/44095637-9e00c3da-9fd9-11e8-94ac-dd66887b59c0.png)

**Comment by tuurma** [comment]
Please note that for nesting categories, eg. in office

![image](https://user-images.githubusercontent.com/449468/44095908-3d7b0dc6-9fda-11e8-9319-c3b76d3cc47e.png)

corresponding category entry has nested categories which represent subcategories

![image](https://user-images.githubusercontent.com/449468/44095992-74ae6ad6-9fda-11e8-96e8-02bc13f5a4c7.png)
