### ISSUE TITLE
display ? in the list of person records

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#188]
After date and place, it is helpful to display the ? in the list of person records, thanks

Example:  Pb8327ce5-6314-4a4a-9540-95d9572a7c76

**Comment by tuurma** [comment]
Date uncertainty mark:

before

<img width="852" alt="screen shot 2018-08-10 at 18 45 25" src="https://user-images.githubusercontent.com/449468/43970665-97b70c7c-9cce-11e8-9d13-c66b07902cfa.png">


after

<img width="861" alt="screen shot 2018-08-10 at 18 51 43" src="https://user-images.githubusercontent.com/449468/43970712-c56767b6-9cce-11e8-9656-30ccdb22e9a7.png">

**Comment by tuurma** [comment]
Place uncertainty mark:

<img width="869" alt="screen shot 2018-08-10 at 19 15 45" src="https://user-images.githubusercontent.com/449468/43971610-05f58256-9cd2-11e8-9ad4-aaae8cddd11e.png">
