### ISSUE TITLE
problem with the display of alternative origin

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#189]
Alternative origin does not show in these three cases. Could we check if this problem appears elsewhere?

P7c90b609-ed2a-4e42-8508-52036a3558b3

Pd2b757c1-9641-4b00-8571-0a8640d24972

Pcaee8019-6591-4391-8ef9-5b60b6227b99

By contrast, in this entry Pf81b6d6f-0a06-4e97-9b79-42e264d3bc90 the alternative origin shows.

**Comment by tuurma** [comment]
I'm a bit puzzled, because in the TEI source the place key is given as 'Berytos' not a proper value of Berytos's identifier

```xml
                    <state subtype="citizen" type="location">
                        <placeName cert="high" corresp="s1" key="Pe2eb53ed-4d77-4fd7-bbc4-78a44bd7aca0" subtype="" type="ancient"/>
                    </state>
                    <state subtype="alternative_origin" type="location">
                        <placeName cert="high" corresp="s1" key="Berytos" subtype="" type="ancient"/>
                    </state>
```

I will run a sanity check for key attribute values that do not have a matching place record and it should shed some light what's the situation.

**Comment by tuurma** [comment]
There are 26 distinct values for state/placeName/@key where no matching place entry exists

These are (cf 
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/sanity-places.xq) for updated listing:

Athens
Delos
Jerusalem
Demetrias (Thessaly, Magnesia)
Rhodes
Rome
Theadelpheia (Egypt)
Thebes (Egypt)
Bostra
Delphi
Berytos
Thessalonike
Heliopolis-Baalbelk
Marathos
Nihatha
Husn Niha
Deir Labas
Heliopolis-Baalbek
Hammara
Ad Ammontem
Demetrias
Thilwos (Syria)


P4474f3e9-1c0f-49e0-b013-424cd33403f0
LGPN_70072
Pa64c24b2-e314-4552-be6c-49bc3b292d18

I will convert the obvious ones and ask what to do with cases like LGPN_70072 afterwards, please bear with me a bit longer (should take about an hour).

**Comment by tuurma** [comment]
Translation table for conversion:

Athens, LGPN_20010: Athens
Delos, LGPN_11270: Delos
Jerusalem, P9ad4b00a-edc2-451b-b3fc-7e8bb96ac6c0: Jerusalem
Rhodes, LGPN_12880: Rhodes
Rome, LGPN_42170: Rome
Bostra, P96234789-1fb5-4246-ba6b-a1f948a1bac6: Bostra
Delphi, LGPN_33503: Delphi
Berytos, P304155a3-e6e3-4aee-a463-aafb0f6986b2: Berytos
Thessalonike, LGPN_40552: Thessalonike
Marathos, P78300fd4-d15c-4785-9a73-faf43cd6677d: Marathos
Nihatha, P495102b3-2ea3-40f1-98f0-a4935fd871f2: Nihatha
Heliopolis-Baalbelk,Pe2eb53ed-4d77-4fd7-bbc4-78a44bd7aca0: Heliopolis 
Heliopolis-Baalbek, Pe2eb53ed-4d77-4fd7-bbc4-78a44bd7aca0: Heliopolis
Hammara, Pc0da80b4-be75-495d-9701-2179a6c11504: Hammara
Ad Ammontem, Pb05d5186-7f84-48db-9c49-e0253db41ed5: Ad Ammontem


Dubious cases:

Thebes (Egypt), LGPN_34698 P597a9a75-6ab0-4d58-998f-c1b7e2426148 LGPN_33161: Thebes
Demetrias, LGPN_33548 LGPN_52880: Demetrias Demetrias

**Comment by JSBLGPN** [comment]
Do I need to do anything?

**Comment by tuurma** [comment]
I'm just running this script:

```xquery
xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";

let $coll := "/db/apps/lgpn-data/data/persons"


let $keys := <keys>
        <entry><key>Athens</key><id>LGPN_20010</id></entry>
        <entry><key>Delos</key><id>LGPN_11270</id></entry>
        <entry><key>Jerusalem</key><id>P9ad4b00a-edc2-451b-b3fc-7e8bb96ac6c0</id></entry>
        <entry><key>Rhodes</key><id>LGPN_12880</id></entry>
        <entry><key>Rome</key><id>LGPN_42170</id></entry>
        <entry><key>Bostra</key><id>P96234789-1fb5-4246-ba6b-a1f948a1bac6</id></entry>
        <entry><key>Delphi</key><id>LGPN_33503</id></entry>
        <entry><key>Berytos</key><id>P304155a3-e6e3-4aee-a463-aafb0f6986b2</id></entry>
        <entry><key>Thessalonike</key><id>LGPN_40552</id></entry>
        <entry><key>Marathos</key><id>P78300fd4-d15c-4785-9a73-faf43cd6677d</id></entry>
        <entry><key>Nihatha</key><id>P495102b3-2ea3-40f1-98f0-a4935fd871f2</id></entry>
        <entry><key>Heliopolis-Baalbelk</key><id>Pe2eb53ed-4d77-4fd7-bbc4-78a44bd7aca0</id></entry>
        <entry><key>Heliopolis-Baalbek</key><id>Pe2eb53ed-4d77-4fd7-bbc4-78a44bd7aca0</id></entry>
        <entry><key>Hammara</key><id>Pc0da80b4-be75-495d-9701-2179a6c11504</id></entry>
        <entry><key>Ad Ammontem</key><id>Pb05d5186-7f84-48db-9c49-e0253db41ed5</id></entry>
        <entry><key>Demetrias (Thessaly, Magnesia)</key><id>LGPN_33548</id></entry>
    </keys>
    
    for $key in $keys/*
    
        let $kval := $key/key/string()
            
        for $k in collection($coll)//tei:placeName[@key=$kval]/@key

return 
    update replace $k with $key/id/string()
```

**Comment by tuurma** [comment]
@JSBLGPN if you could have a look at http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/sanity-places.xq and tell me if I can assign values automatically for remaining entries.

For Thebes and Demetrias there are 2 places each, so I don't know which one to choose. For other places I have no candidates even, maybe place records need to be registered for them first.

**Comment by tuurma** [comment]
sorry, just noticed that for Demetrias in Thessaly I can automate this without problem, will do so in a minute.

**Comment by tuurma** [comment]
For remaining entries if they are just singles it's probably best to reassign the place of origin for them manually. For places with more than one person in them if you could give me the place id (or place name and region), I'd be happy to run my script on them.

**Comment by JSBLGPN** [comment]
I'm trying to understand.
There is a problem with Thebes from Egypt: do I need to reauthorise this place? It is authorised and I have tried to reassign the following individual to Thebes (Egypt) but it does not seem to work...

http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P9b460e71-c2e9-433c-be06-bf330bf06ea4

**Comment by JSBLGPN** [comment]
All these entries have been manually reassigned except: the one from Thebes (Egypt)

There are more than one person in them for Antioch and Arethousa (Syria)
LGPN_70050
P2e3229f6-56b1-4d6a-a457-74e436c77971

**Comment by JSBLGPN** [comment]
This problem is not solved in the old list of person records.

**Comment by tuurma** [comment]
I have reassigned the one from Thebes (Egypt)

old list:

![image](https://user-images.githubusercontent.com/449468/44045097-ceea903c-9f27-11e8-916e-a5184b9c1a58.png)

new list:

![image](https://user-images.githubusercontent.com/449468/44045144-ee035c4c-9f27-11e8-84ca-9407e83e234b.png)

**Comment by tuurma** [comment]
One entry still remains to fix: http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/?sort=bibl&browse=pid&filter=Pec1770c8-85e9-4d70-a618-cebc6e638707

In the old list I can see alternative origin places properly. Maybe there is some caching issue, could you please check if refreshing the page with Shift+F5 (if I remember the shortcut correctly) helps?

**Comment by tuurma** [comment]
Now all entries are fixed so closing this issue.
