### ISSUE TITLE
Linking old lgpn/browse to new editor

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#191]
Could records in the older http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn/browse.html interface be linked so that when opened they will use the new editor (http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml), and we can take advantage of its new features?

**Comment by tuurma** [comment]
Added this feature, now even from old application entries will always open in a new editor. Please let me know if any problems occur.
