### ISSUE TITLE
still problem with LGPN editor to display new changes of old forms

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#194]
Example 
I change this yesterday but not in LGPN editor...
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P813ae6d6-be1d-4551-a56d-05474648436a

**Comment by JSBLGPN** [comment]
sorry I changed this entry yesterday (using the "old" database), but the change is not not displayed in LGPN editor.

**Comment by tuurma** [comment]
Forgot to change links for the name and relationships - only did the link for the edit icon previously, sorry about that omission. It's fixed now, I will trigger reindexing now and it should stop the issue reappearing.
