### ISSUE TITLE
display person records LGPN editor

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#195]
is it possible to display, in the list of person records, to display in the column relationships,

1. "father of" (at the moment we only have child of)
2. the partial names for which they are no entries: example here in the entry for Apollonia see box relationship person Poll--
(Apollonia: P779fc235-920c-4006-8d2d-f46b05d4ee2b)

thanks

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/44423720-1b2e7e80-a587-11e8-881c-0ee0ad1e0f3f.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/44423896-9abc4d80-a587-11e8-803c-033bf8d298c2.png)
