### ISSUE TITLE
list of person records: certainty for name ?

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#197]
Can we show a ? in the list of person records after a name which is dubious? (like you did for place and date)

Like: Nolis
P3aedf755-1de9-4fae-b8af-5cd7a036bc65

thanks

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/44425140-5337c080-a58b-11e8-9324-48006847f54b.png)
