### ISSUE TITLE
LGPN editor down today...

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#200]
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/

the message is: an error has been generated by the application and we have been unable to use it...

**Comment by tuurma** [comment]
I'm on it, thanks for letting me know.

**Comment by tuurma** [comment]
Could you please check if it works for you again?

**Comment by JSBLGPN** [comment]
still not working

**Comment by tuurma** [comment]
I see, trying to reproduce when it actually fails. Please bear with me few more minutes.

**Comment by tuurma** [comment]
Could you please check again?

**Comment by JSBLGPN** [comment]
yes it works. it is very slow though, thanks.
