### ISSUE TITLE
search relative for relationship in input form

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#202]
If you look for a relative with the name Αβγαρος (Abgaros) with a reference in RE, the RE notice number which appears in brackets does not show, so it is impossible to distinguish between Abgaros RE (3), Abgaros RE (74), etc...

I think this is a problem that you solved in the past but reappeared.

**Comment by tuurma** [comment]
Indeed, this was a regression, now fixed

<img width="547" alt="image" src="https://user-images.githubusercontent.com/449468/49404484-de5e5000-f74f-11e8-8833-5127bc99ebb6.png">
