### ISSUE TITLE
About notifications

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#203]
Is there a way that the three of us receive a notification when a problem is solved, so we are all kept informed about resolved issues and updates? At the moment only the person who write the issue is informed. Thanks

**Comment by tuurma** [comment]
@JSBLGPN @michaelzellmann 

You could subscribe to "watch" this repository (see screenshot below) and you will get email notifications of all comments, new issues and status changes.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/449468/45295396-d8652400-b4fe-11e8-9265-b24a816b346f.png">
