### ISSUE TITLE
list of person records: display: place names: territory, area, etc.

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#204]
Example: the individual called Naaras is under Tripolis in the list of person records, but it would be helpful to have Tripolis (terr.) to indicate that he is actually from the territory of Tripolis as the input form indicates.

http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P8a5825c3-e426-4894-a5ab-05f5706c5e9f

**Comment by tuurma** [comment]
Now added

<img width="692" alt="image" src="https://user-images.githubusercontent.com/449468/45299494-17e63d00-b50c-11e8-9ac4-66c496212936.png">
