### ISSUE TITLE
display of ? after name: problem when two names are queried

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#205]
Example: Naaras Tartos: both names are queried in the input form, but in the list of person records only Naaras is shown with ?
 
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P8a5825c3-e426-4894-a5ab-05f5706c5e9f

**Comment by tuurma** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/449468/45297919-30078d80-b507-11e8-934d-a2afc629900b.png">

**Comment by tuurma** [comment]
Bug was not really in the display of the certainty markers but in the editing form - certainty field was always linked to the first name of the person, so the value displayed in the form and recorded in the database might have differed (cf xml snippet below with `cert='high'` for the second name). I have fixed this now and adjusted Naaras Tartos record.

```xml
                    <listNym>
                        <nym ana="semitic" cert="low" n="1" nymRef="Νααρας" type="">
                            <seg type="linking"/>
                            <form type="attested">
                                <persName ana="Nom" corresp="s1" n="1" xml:lang="grc">Νααρας</persName>
                            </form>
                        </nym>
                        <nym ana="" cert="high" n="2" nymRef="Ταρτος" type="">
                            <seg type="linking"/>
                            <form type="attested">
                                <persName ana="Nom" corresp="s1" n="1" type="main" xml:lang="grc">Ταρτος</persName>
                            </form>
                        </nym>
                    </listNym>
```

<img width="641" alt="image" src="https://user-images.githubusercontent.com/449468/45299087-c1c4ca00-b50a-11e8-88f9-b1f853e773f9.png">
