### ISSUE TITLE
list of person records: showing 50, 100, 500 and all individuals on the screen

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#210]
1. the old list of person records has a box with show 50, 100, 500 and all entries. Instead of "show", use "display"
![show](https://user-images.githubusercontent.com/18262359/47728299-f70dae80-dc55-11e8-805c-a23ccb738c91.PNG)

2. If we select 50 entries one page should have exactly 50 entries and page 2 entries 51-100, page 3 101-50 like in the LGPN online search (picture below). At the moment entries in page 1 and 2 overlap and it is time consuming. Add an arrow at the bottom of the page as well, so we don't have to scroll up to go to the next page.

![pages](https://user-images.githubusercontent.com/18262359/47729454-173e6d00-dc58-11e8-9d11-a987f6ac3be3.PNG)

**Comment by tuurma** [comment]
search for e.g. Θεοτεκνοσ shows 2 pages, 26 matches, but page 1 already displays all 26 thus moving to page 2 which starts at result 21 gives same hits which were already seen at the end of page 1

**Comment by tuurma** [comment]
I have found a discrepancy which caused the overlap and fixed it. Adjusted the display to show 50 documents per page, thus for bishop search (1104 matches) we'll have 23 pages total.

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/449468/53795508-6eb85680-3f32-11e9-9d6c-57cfe679c32e.png">

**Comment by JSBLGPN** [comment]
thanks. very helpful
