### ISSUE TITLE
delete places

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#219]
place listing should expose the Delete function for places that have no references or nested places

**Comment by tuurma** [comment]
Place catalogue

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/449468/52855246-2242dd80-3121-11e9-93f3-065b2fd83011.png">

**Comment by tuurma** [comment]
Confirmation dialog

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/449468/52855294-4a324100-3121-11e9-99e1-6221be96bf8a.png">

**Comment by JSBLGPN** [comment]
Places with 0 persons don't show up in the list. But we need to delete them because they appear in the drop down list in entry form. Example: Kafr Hawar below. Can they appear in list of places?

![duplicate](https://user-images.githubusercontent.com/18262359/53080885-93074280-34f1-11e9-83c7-01fcb774638b.PNG)
![duplicate2](https://user-images.githubusercontent.com/18262359/53080892-969ac980-34f1-11e9-868a-b8b7bb5baa30.PNG)

**Comment by tuurma** [comment]
Both Kafr Hawar can be seen in the Place catalogue > K table which allows to delete the superfluous one. Lists of place names under the Proofing menu are always limited to Volume 6, thus do not show places with 0 persons connected. Does that help?

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/449468/53096092-9bc23d80-351e-11e9-882d-f1adb20faf7a.png">

**Comment by JSBLGPN** [comment]
Ok...when I refresh by "regerenating list of place names" unfortunately it does not regenerate immediately...is there a way to regeneration that?

**Comment by JSBLGPN** [comment]
Sorry...forget about my last comment. it is working fine.

**Comment by JSBLGPN** [comment]
Regenerating the list of places is inconsistent. Sometimes it works, sometimes it doesn't. Maybe I have not discovered the logic yet...

**Comment by tuurma** [comment]
If you see the message below after clicking Admin > Regenerate list of places, then the document storing nesting relationship between places should be successfully regenerated and stored on the server. 

<img width="676" alt="image" src="https://user-images.githubusercontent.com/449468/53237544-3f365e00-3697-11e9-9874-fbb9e4ef1694.png">

Bear in mind that this operation just regenerates the index, not the list which you can see. Unfortunately, your browser may still have a cached version of the page with list of places (http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/templates/subpages/placesNested.html), so you'd need to refresh that with Shift+Reload.
