### ISSUE TITLE
place catalogue: is Z in?

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#222]
I m not sure Z is in the place catalogue since the list is too long for the screen...

**Comment by tuurma** [comment]
Thanks for letting me know - indeed, Z is unreachable, trying to fix the styling. I will also add the missing letters.

**Comment by tuurma** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/449468/53241111-f388b200-36a0-11e9-9ddc-534ccdd3d041.png">

Hope this helps with visibility.

**Comment by tuurma** [comment]
Please note that Shift+Reload may be required to clear the browser cache and see new styling of the dropdown menu.

**Comment by JSBLGPN** [comment]
I can see Q but I cannot see letters after S

**Comment by tuurma** [comment]
Sorry, forgotten about this. Would you mind taking the screenshot for me?

**Comment by JSBLGPN** [comment]
Now it's ok for me, thanks :
![alpha_places](https://user-images.githubusercontent.com/18262359/53514260-3a224600-3abf-11e9-890e-5eecc96f6901.PNG)

**Comment by tuurma** [comment]
Great, then it must have been some caching issue that changed styles were not loaded at first.
