### ISSUE TITLE
how to search status?

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#224]
it would be helpful to design something which would unable us to retrieve data from status, religion, profession, office, Roman world. Example be able to retrieve all the bishops...
Thanks

**Comment by tuurma** [comment]
Just added a new filtering option called status. Please let me know if it suits your needs

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/449468/53641017-0b76ad80-3c2e-11e9-8033-21740817e083.png">

**Comment by tuurma** [comment]
I'm just reindexing which will take few more minutes. There should be 1100 entries for bishop in total.

**Comment by JSBLGPN** [comment]
Thanks. Yes that works for me.
