### ISSUE TITLE
place names not appearing in book

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#225]
As discussed previously there are place names that won't appear in the book and we will need a solution for that. In the form there is a box "grouping"...is it meant to solve this? if yes does it work?
Thanks

**Comment by tuurma** [comment]
I've been working on it, can't recall 100% what the status was there. Could you please give me an example of a place that should only be folded into it's parent area?

**Comment by JSBLGPN** [comment]
For examples Kafr Buhum or Esfin will not appear in book as such but as under Amathe (territ.)

![notinbook](https://user-images.githubusercontent.com/18262359/53645309-7fb25080-3c30-11e9-9841-202d41f67348.PNG)

**Comment by tuurma** [comment]
@JSBLGPN this is the current treatment, seems incorrect, should be Amathe (territ.) and no mention of Kafr Buhum, right?

<img width="813" alt="image" src="https://user-images.githubusercontent.com/449468/59438206-58ece400-8df3-11e9-8b4a-804f888858d9.png">

<img width="895" alt="image" src="https://user-images.githubusercontent.com/449468/59438226-63a77900-8df3-11e9-95e1-5b246231e955.png">

**Comment by tuurma** [comment]
corrected version

<img width="987" alt="image" src="https://user-images.githubusercontent.com/449468/59440601-89368180-8df7-11e9-9bb3-3af94d662982.png">

**Comment by JSBLGPN** [comment]
Yes. That is correct, not all the place names will appear in book. I have a list of place names for the three regions I have dealt with (Syria, Phoenicia and Kommagene), that will not appear in the book. At the moment I don't think we have a button in the database to select which ones won't appear in the book.

**Comment by tuurma** [comment]
Thanks. Please use 'group under parent area' for such places. I have adjusted the .tex file generation as shown above to take this setting into consideration

<img width="930" alt="image" src="https://user-images.githubusercontent.com/449468/59442048-c8fe6880-8df9-11e9-8f47-8de7e4515f9b.png">

**Comment by JSBLGPN** [comment]
Thanks. It will take a bit of time. There are many place names.

Would it be possible (if not too time consuming for you) to make place forms accessible via the nested list and add an icon showing the status of each place in the list of nested place? So we don't miss places and once done it appears in the nested list. 

![Buhu,](https://user-images.githubusercontent.com/18262359/59442725-ae74c100-8df2-11e9-9c08-383a6e995229.png)

**Comment by tuurma** [comment]
Added visual clue that a place will not appear in the book, it is slightly dimmed <img width="1392" alt="image" src="https://user-images.githubusercontent.com/449468/62243499-ae9a4180-b3dd-11e9-8777-767e8ff552bc.png">
