### ISSUE TITLE
search for a place and its nested places in lgpn editor

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#226]
It would be useful to be able to retrieve all the people under a place and its nested places. So ideally we would be able to make two different kind of searches. 
Example with Syria: the one search would retrieve people assigned to Syria, the other all people assigned to Syria and its nested places.

**Comment by tuurma** [comment]
Implemented with 'Region' search

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/449468/62858600-08164080-bcfb-11e9-957c-f81f26620823.png">
