### ISSUE TITLE
[Relationships] autocomplete problem

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#230]
Error message "loading failed"

![image](https://user-images.githubusercontent.com/20699164/54809742-13999a00-4c7c-11e9-97fa-512c6dbb5b8e.png)

**Comment by tuurma** [comment]
Fixed now, sorry, my bad, I've been refactoring some modules and left the old reference.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/449468/54905276-ef8ac280-4ee0-11e9-9830-6ba736fb24c0.png">
