### ISSUE TITLE
A map of authorised place names

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#231]
It would be helpful to be able to produce a map of authorised toponyms with coordinates. This would help to save a lot of time when checking nesting.

Thanks
JS

**Comment by tuurma** [comment]
Just checked, in the database 2176 places out of 6837 total have their geocoordinates recorded. I can still produce the map, of course, but it will be incomplete.

**Comment by JSBLGPN** [comment]
Is it possible to signal in the nested places those without coordinates?

**Comment by tuurma** [comment]
Sure, here's first attempt

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/449468/55639097-ec3ce400-57c8-11e9-99a7-72cccef8c7b4.png">

**Comment by tuurma** [comment]
Map is still in the works, expect to finish today.

**Comment by tuurma** [comment]
Some geolocations included comma which is not supposed to be there in TEI, requires cleanup with

```
declare namespace tei="http://www.tei-c.org/ns/1.0";

for $i in collection('/db/apps/lgpn-data/data/places')//tei:geo[contains(., ',')]
return 
    update value $i with translate($i/string(), ',', '')
```

In one case of Kišʻāla  xml:id="Pe01c5b35-8d0e-434e-a96a-affa257a4765" geolocation was given in natural language as `<geo>Gabal Halaqa, 2km west of Dana</geo>` which should be moved to `<alt/>` tag. I will do this one manually.

**Comment by tuurma** [comment]
@JSBLGPN I have a map for all the places but it's looking a bit overwhelming and I'm not sure it's that helpful for checking nesting of places because with so many points on the map it only zooms or moves super slowly. I could link the map to nested/alphabetical place list so it only shows descendants for a particular place, would that make sense?

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/449468/55797101-ddf20f00-5acb-11e9-8803-9cd3fc754ee8.png">

**Comment by tuurma** [comment]
This is how results for one place (and all its descendants) would look like when choosing eg Adraa in Arabia  Pbb7aaaf6-71f5-4729-a2f3-1a16adab0d20

<img width="732" alt="image" src="https://user-images.githubusercontent.com/449468/55798332-f57ec700-5ace-11e9-935d-011bea6593dd.png">

**Comment by JSBLGPN** [comment]
That looks strange. Don't we have coordinates only for places in volume 6? The map covers mostly Turkey (volume 5)...the second map is certainly not Arabia, but Turkey....

The first map won't be very helpful, but the second one will be helpful for checking nested places. 
Thanks

**Comment by tuurma** [comment]
@JSBLGPN All places registered for previous volumes have been imported and where they already had coordinates we still have them. If second kind map is helpful I will link it to the nested/alphabetic list of places so a click on the map marker will redirect to the map for the place with all its descendants. I was also thinking about assigning different colour for direct children of a place and another one for more distant descendants. If all goes well I will deploy it to the server tonight so you can test tomorrow.

**Comment by tuurma** [comment]
Added some colour coding to help determine what is what. The map below shows entries for Hauran-Aurana | P39739c38-271c-437b-ac66-10b74e634a9d

Hauran-Aurana is shown in red, its direct children in green and all further descendants in blue. It's not that common that we have such a deep nesting so for other places we may see only red and green markers and that's normal.

**Comment by tuurma** [comment]
Sorry, disregard previous screenshots, I treated longitude as latitude so the points were shown in wrong places ;-) Here's Hauran-Aurana again

<img width="944" alt="image" src="https://user-images.githubusercontent.com/449468/55901586-eb8dbe80-5bc9-11e9-82d9-2ad0b6c015de.png">

**Comment by tuurma** [comment]
Deployed on the server a moment ago, hope that helps in your work, let me know if I can adjust the map so it better fits your workflow.

**Comment by tuurma** [comment]
Proper map for Arabia

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/449468/55906374-6cea4e80-5bd4-11e9-91b3-3eff9ae4665c.png">

**Comment by JSBLGPN** [comment]
Thanks. I am not sure if I did something wrong, but the database failed to produce any map: I went to nested places and alphabet. list of places, clicked on the little blue icon, but nothing happened...

**Comment by tuurma** [comment]
I was testing on Chrome and Safari and both look fine, unfortunately I don't have Internet Explorer to test. Do you mind trying this link http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/map.html?place=LGPN_33801 ? 
If it still doesn't work for you could you please copy a link from the browser for me?
Should produce an image like this:

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/449468/55981052-2e1ccd00-5c96-11e9-9b2d-e1ea137eccc2.png">

**Comment by tuurma** [comment]
Hi @JSBLGPN I know what it is - forgotten that I already run into it myself and fixed it but due to some strange problem I am unable to access LGPN server. It already happened on Wednesday and I did ask Diggory for help but it is something weird that occurs since months at seemingly random times for me.

**Comment by JSBLGPN** [comment]
Thanks Magdalena! It works. I will test further next week as I am away until Tuesday.

**Comment by JSBLGPN** [comment]
In the place form some regions like Syria or Phoenicia (authorised in the old system) have no box for coordinates. Would it possible to add that box, so we can display the map?
Thanks, JS

**Comment by tuurma** [comment]
Added

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/449468/56968953-66f8e500-6b64-11e9-935a-a58c21e96ee1.png">
