### ISSUE TITLE
problem loading biblio data

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#232]
![image](https://user-images.githubusercontent.com/18262359/55637165-58651b00-57bc-11e9-8ea2-a623bfb10c5d.png)

I am not quite sure why it does not work...but this is problematic

**Comment by tuurma** [comment]
I can reproduce this, didn't find a cause yet, looks like any other bibl entry - I'll keep looking

**Comment by tuurma** [comment]
Finally found it - there was an obsolete partial list of bibliography entries present in the collection duplicating some titles, like Dussaud but also SEG and few others which led to problems retrieving the correct entry by id. Now cleaned and fixed.

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/449468/55786915-7c26aa80-5ab5-11e9-9419-279a1ac4ba6e.png">
