### ISSUE TITLE
display of ? after date in list of person records

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#233]
like we have for uncertain place names.
Thanks JS

**Comment by tuurma** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/449468/56971480-9cec9800-6b69-11e9-9aa2-4367303f3353.png">

**Comment by JSBLGPN** [comment]
is it possible to place the question mark after centuries just as dates?
thanks

![image](https://user-images.githubusercontent.com/18262359/57010430-73c51980-6bf4-11e9-9bc4-b435ee495da6.png)
