### ISSUE TITLE
ambiguous places

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#234]
We have a category of place names that cannot be assigned to any region and so have no coordinates. We would put them in Other. The reason is that there are several homonyms like for example Nikopolis. Is it possible to create an 'ambiguous' region. So in the drop-down list we have one for Nikopolis (amb.)...
One example is Apollonides from Nikopolis (P53659bcf-f786-4fe6-bcd3-9fdc27dfd41e) and his father. As we don't know from which Nikopolis he came, I would use Nikopolis (amb.)
Thanks

**Comment by tuurma** [comment]
Do I understand right, you'd like there to be a region called (amb.) and you'd create another Nikopolis in this region (so there would be even more places called Nikopolis), like in the image below

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/449468/56972184-d2de4c00-6b6a-11e9-819c-2102d7eddb41.png">

**Comment by tuurma** [comment]
Added (amb.) as a place, so it can be selected for a region. Please let me know if this fits your use case.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/449468/56972544-76c7f780-6b6b-11e9-864b-3cd46b58c185.png">

**Comment by JSBLGPN** [comment]
We do not need double brackets, so it could appear as Nikopolis (amb.)

![image](https://user-images.githubusercontent.com/18262359/57010132-02389b80-6bf3-11e9-8590-610eafdc0bbb.png)
