### ISSUE TITLE
display of dates: error

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#235]
On the list of person records both 1B-1A and 1B/1A are displayed as 1B/1A. They have different values : 
1B-1A = 100BC-100AD
1B/1A = 25BC-25AD

so 1B-1A should appear as 1B-1A and not as 1B/1A

thanks

**Comment by tuurma** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/449468/56966995-9148a380-6b60-11e9-9f66-14ab14063dfe.png">
