### ISSUE TITLE
A relative with ID number only

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#236]
The relative of the man below is showing his ID number only. There must be something wrong here...

![image](https://user-images.githubusercontent.com/18262359/56582904-3d721380-65d0-11e9-966c-15df1325588d.png)

![image](https://user-images.githubusercontent.com/18262359/56582872-2af7da00-65d0-11e9-98dd-db2faeee1a02.png)

**Comment by tuurma** [comment]
Person Id: P855da7c0-be3e-4ba3-b242-f12b6b44a01a

I have checked that and indeed there's no Person with an ID of V6-34621 which is why it can't be displayed correctly. It's probably my fault resulting from preparing for the switch to LGPN-style identification numbers. There are in total 21 entries in the database that all refer to V6-34621. If you could help me identify who this should be (ie who the real father of Maximus is) I will replace the mistaken references.

**Comment by JSBLGPN** [comment]
The name of Maximus is unknown so there should be no addition in relative. I deleted the V6-34621 id.
Thanks

**Comment by tuurma** [comment]
<a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pa81d474b-3b50-464c-9567-fe506cf86253">Ἀγαθοκλῆς</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P504a9f80-9509-462d-b6d4-86031244a09b">Ταννος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pb4d8c6e4-d242-4059-9f0a-cb37fbd2d671">Ανναμος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pb90569c2-6153-4c2c-bc06-d62d1f22f08f">Φολσκιανός Σεουῆρος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P484c0f69-7d97-4205-80be-49a3076940e8">Πρόκλος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P41c41477-c978-4d84-95aa-d8f025eb7d92">Μάλχος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P4054dfd4-a281-4129-8d8a-0f62f1f2f467">Ασπαβεδης</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pa93fe513-72f4-4c55-b5cb-0a1fbe614973">Γαιρηλος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P21f5b2e8-bb95-47be-b511-a0f880f6fc91">Μαλχίων</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P217be5ed-379d-483b-93dc-d9da9a8fe387">Θεόδωρος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P977e6417-39cf-482b-b755-67c5ac6cb1dd">Κερεάλιος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P167ce47c-efae-4ceb-a001-62dfac0927ac">Χεειλος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P090df539-3d4d-4077-b43c-59a2e3864798">Λούκιος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P6d471898-2a9a-4dd2-8934-99982282077d">Καιουμος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P02750af4-768a-4331-9e8f-a1719f054e42">Γερμανός</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pc2438176-ed26-4ab1-8215-3a2c3c8b177a">Ζηνόδωρος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pa617627c-0fb0-4a66-9a63-05764dd28e37">Σαχρηλος</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pa63f38fe-8968-47e5-ba14-9b938fd78a63">Κλαυδία</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P534c5f30-29cb-404d-b646-e4849b1088af">Εβρικανης</a>
    <a href="http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=P589978e6-d89c-4b85-9e45-8819b28f6403">Νόμος</a>

**Comment by tuurma** [comment]
Above is a list of the other cases where V6-34621 is referred to, if you'd like to have a look

**Comment by JSBLGPN** [comment]
The system failed to load data for Theodoros (Θεόδωρος)...can we check the reason? Thanks.
I changed the others thanks

**Comment by tuurma** [comment]
There are 2 registered

<img width="645" alt="image" src="https://user-images.githubusercontent.com/449468/56971777-28662900-6b6a-11e9-9bab-a489b47dbbf5.png">

You can find both searching by Person Id P217be5ed-379d-483b-93dc-d9da9a8fe387 and delete the wrong one

**Comment by tuurma** [comment]
It's been meanwhile fixed, so closing

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/449468/58014167-7b435880-7af8-11e9-8236-2ccde9c0abb4.png">
