### ISSUE TITLE
parent of*

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#237]
Parent of* is a way for us to encode the name of a father/mother whose name is incomplete, so in the book this will only appear in the final brackets under the name of the son or daughter: example Nikon of Larissa (s. --ERTOS), meaning Nikon is a son of a man whose name ends in ERTOS.

Before the choice "parent of*" was created in the input form, we entered a series of such cases under "other relative of". Would it be possible to produce a list of people who have "other relative of"? So we can check and change accordingly.

Thanks a lot

![image](https://user-images.githubusercontent.com/18262359/57072273-09d07100-6cd5-11e9-9b1b-fed374979aac.png)

**Comment by tuurma** [comment]
There are bit more than 300 cases, cf. http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/otherrelative.xql
