### ISSUE TITLE
Failed to load data

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#239]
there are these two individuals called Chares (Χαρης) and their relatives (Diomedes) for which we cannot access data (see pic). I have noticed that the two Chares have the same ID number (P3b669daa-e1b9-47d8-930a-109d52314e09 ). One Chares is placed in Other, the other is in vol 6. The Chares and Diomedes put in Others need to be deleted, and I would like to access Chares and Diomedes in vol 6 to check their place of origin. Thanks

![Chares](https://user-images.githubusercontent.com/18262359/58013431-809ba580-7aee-11e9-8262-89637283feee.png)

**Comment by tuurma** [comment]
Hi, if you can find them in the list (eg searching by ID) then just clicking on the delete button will remove the corresponding entry (but not the other one, despite ID being the same). Sometimes requires reloading the page (Shift+Reload) to see that indeed only one is left.

Just did it for Chares and Diomedes from Other, so you can access the ones in V6


<img width="1193" alt="image" src="https://user-images.githubusercontent.com/449468/58013827-c315b000-7af7-11e9-8e28-ab202bc99161.png">

**Comment by JSBLGPN** [comment]
Of course, thanks.
