### ISSUE TITLE
absence of family term in FB

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#240]
I think there should be an abbreviation for grand-father in the final bracket column as Maximus Modestus Sentianus is the grand pa of Taurus Sentianus...

![Sentianus](https://user-images.githubusercontent.com/18262359/58017799-01f83580-7af9-11e9-9bec-ae7744e36f55.png)

**Comment by tuurma** [comment]
Labels for grandfather/grandmother were missing

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/449468/58429942-c684da80-80a7-11e9-9942-7401f451ba73.png">

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/449468/58429967-d7355080-80a7-11e9-9d00-f3ec823d9517.png">
