### ISSUE TITLE
references structure and tidy up

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#243]
As mentioned in https://github.com/eXistSolutions/LGPN/issues/59#issuecomment-492225067 I have prepared a list of all bibliographical abbreviations available at http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/listBiblAbbr.xq

There are some inconsistencies evident, eg. treatment of multi-volume references (compare IGLS vs SEG and also handling sub-volumes within IGLS)

<img width="258" alt="image" src="https://user-images.githubusercontent.com/449468/59442792-352d9c00-8dfb-11e9-826d-327c30a261b4.png">

<img width="167" alt="image" src="https://user-images.githubusercontent.com/449468/59442830-44ace500-8dfb-11e9-849f-a1104e1bc901.png">

My postulates would be:

* [x] decide on uniform treatment of multi-volume references
* [ ] explicitly mark parts of the abbreviation which should be displayed in small-caps using _ marker (like we do + for italics)

If we agree on that I could automatically convert existing data. @JSBLGPN I'd appreciate your opinion

**Comment by JSBLGPN** [comment]
With the IGLS abbreviations we did not follow a pattern and so we will need to change that. 

For small caps, can we use the patterns in the reference form?

![smallcap](https://user-images.githubusercontent.com/18262359/59449462-044f6600-8dff-11e9-96a8-56525f719434.png)

There are three cases where smallcaps are required:
FASCICULEPAT eg. FD III (4) --> III in smallcaps
ROMANPAT eg. SEG XXX --> XXX in smallcaps
VOLUMEARAB eg. IC 4 p. 45 no. 1 --> 4 in smallcaps

One exception is IG (the abbreviation for Inscriptiones Graecae [very many volumes]). It used to have its own pattern and each volume had to be authorised separately. But small caps are needed here as well. Eg. IG XV 1458
Smallcaps are not required for IG XV 1458 II, 34....II meaning here column 2.

**Comment by tuurma** [comment]
as mentioned in #253 IGLS entries need to be automatically converted from specific volumes to generic `IGLS`, while the volume number should be added in the *details* field

eg. `Μαρθοον | V6 | Sūsanbāṭ (mod.) | ?ii AD | IGLS I 230a, 3 (inscr. stone )`

currently TEI source looks as follows

`<ref ana="" subtype="" target="IGLS_I" type="inscr_stone">230a, 3</ref>`

should be

`<ref ana="" subtype="" target="IGLS" type="inscr_stone">I 230a, 3</ref>`

<img width="556" alt="image" src="https://user-images.githubusercontent.com/449468/63094916-0b633380-bf6a-11e9-9ca7-181ed37af6c1.png">

**Comment by tuurma** [comment]
@JSBLGPN List of IGLS volumes for automatic conversion, please let me know if this is ok

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/449468/63095661-11f2aa80-bf6c-11e9-8dea-18e49a4c9834.png">

**Comment by JSBLGPN** [comment]
Ok. Perfect.
Thanks

**Comment by tuurma** [comment]
Converted all IGLS entries

[convertIgls.log](https://github.com/eXistSolutions/LGPN/files/3508945/convertIgls.log)

**Comment by tuurma** [comment]
@JSBLGPN Here's a list of bibl entries which contain `_`, a marker for small caps in abbreviation. http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/biblWithUnderscore.xql

It looks mostly ok to me, with exception of Inscribed Economy and Studies Jordan, where underscore should really be space, I think (in abbreviation, we still need underscore in ID).

<img width="930" alt="image" src="https://user-images.githubusercontent.com/449468/63158650-01007280-c01a-11e9-9a27-496ec5539482.png">

**Comment by tuurma** [comment]
Sorry, just a note that I needed to regenerate metadata index after automatic IGLS conversion, it may take a while (approx 1h)

**Comment by JSBLGPN** [comment]
Yes. all smallcaps with the exception of 20-21-34-43 where _ should be a space. Number 40 is also wrong: PIR_2 should be PIR^2 so superscript.
Thanks

**Comment by tuurma** [comment]
Corrected 20-21-34-43-40 (thus these disappeared from the list now)
