### ISSUE TITLE
[print] abbreviations

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#244]
# General
## Type

* [x] fictitious = fict.
* [x] heroic = her. 
* [x] These need to go at the very end of the final brackets

# Primary Sources

* [x] Source:  Inscription Stone, Literary Text, Papyrus, Figurine, and Tablet are NOT going to the book.
* [x] All other sources are mentioned in the book in full (exception : amphora below). 
* [x] We would need to add a category called diploma (abbreviated as “dipl.”). For the moment, this info has been recorded in source characteristic. If you send me a list, I will do the change. 

Materials: Stamp does not go to the book if one of the following “materials” is selected: amph. (use this abbreviation for amphora), tile, pot, brick, pithos (ignore all other materials for the book)

> please confirm if I understand correctly: only if `stamp` is selected but no subcategory or subcategory is `official` or `other` it goes in the book?
> would it be acceptable to say that a subcategory always has to be marked (I could run it automatically) and then my task would be simpler - I would only mark `other` and `official` as going into the book in the taxonomy list and would not have to make a special case in the application code, which is easier to maintain in the longer run

Multilingual: 
* [x] Bilingual = biling.
* [x] Trilingual = triling.
This info comes right after the source and ref. details in brackets

# Status

Status: 
* [x]  All in with the exception of “resident”
- Abbreviations for the following statuses
* [x] freedman = freed.
* [x] imperial freedman = imp. freed.
* [x] tes epigones = t. e.
* [x] epidamia = epid.

 - If there is a place indicated in bracket, it should not appear in the book. 

> not at all or the name of the place should not appear? statuses are: `mothax, hypomeion, penestas, oiketes`

-For slave and freedman: a level of certainty was requested but not implemented, so until now these cases have been put in FB as slave? or freed.?
* [x]  Correct “trofimos” in “trophimos”.  
* [x] Subcategory: the only one that goes to the book is oikogenes (status: slave) abbreviated “oikogen.”  

> removed imperial slave from print output (also subcategory of slave)

* [ ] uncertainty level missing

# Profession
They only ones that go to the book are:
* [x] architect, coin engraver, doctor, fabricant amphoras (abbr. “fabr.”), hetaira (abbr. “het.”), mosaicist, painter, potter, sculptor.

# Office
The only ones that go to the book are:
* [x] demiourgos, dynast, king, oikist, queen, regent, stephanephoros (abbr. “steph.”), tyrant
* [x] subcategory: “epon. arch.” (for eponymous archon), “fed. arch.” (for federal archon) and “fed. strat.“ (for federal strategos)

# Religion
The only ones going to the book are:
* [x] hierodoulos/e (abbr. “hierod.”), mantis
* [x] subcategory Christian: presbyter (abbrev. “presbyt.”), anagnostes (abbrev. “anagn.”), deacon (Male), deaconess (if Female), archdeacon, subdeacon, bishop (abbr. “bp.), chorepiskopos (abbrev. chorepisk.), archbishop (archbp.), archimandrites and hegoumenos should appear as “abbot”, patriarch should appear as “archbp.”, saint (same as slave above: we should have had a level of certainty, so until now saint? have been encoded in FB)
* [x] subcategory Jew: presbyter (“presbyt.”), deacon, rabbi, archisynagogos (abbrev. “archisynag.”)

* [ ] uncertainty level missing

# Roman world
The only ones going to the bokk are
* [x] emperor (abbr. “emp.”), gladiator (abbr. “glad.”)

# Secondary sources

* [x] Source: in brackets after the secondary sources and details: location (“lcn.”), name, date, relationship (should appear as “family”), stemma. 

# Relationships

* [x] Relationship: only “s., d., f., m.”. If gender is unknown, the ambiguity is expressed in the relationship as “s./d.” or “f./m.”. 
* [ ]  =?= : ~~should appear as =? followed by the number of the individual in brackets. If this relationship links two individuals with different names, example: Sergis and Sergios (=? Σέργιος (4))~~ (extracted into #255) .
* [x] Relationship types: natural = nat. and adoptive = ad. Natural is only expressed in conjunction with 
Adoptive. Example: a son whose natural and adoptive fathers are known will appear as  Z. s. (nat.) of X. and s. (ad.) of Y. in FB.

**Comment by tuurma** [comment]
General: Type

<img width="973" alt="image" src="https://user-images.githubusercontent.com/449468/59450567-c3a91a00-8e09-11e9-93be-ca060c6280d1.png">

**Comment by tuurma** [comment]
Added a `diploma` category for primary sources

<img width="373" alt="image" src="https://user-images.githubusercontent.com/449468/59500703-4b3e6980-8e9a-11e9-9608-88d26a88b22e.png">

**Comment by tuurma** [comment]
There are 69 entries where source characteristic reads `diploma` and I could update these automatically.

**Comment by JSBLGPN** [comment]
If you could do automatically, it would be very helpful

**Comment by tuurma** [comment]
@JSBLGPN I have included some questions and remarks above (visualized in the grey blocks) but I think most of the abbreviation handling is now done

**Comment by JSBLGPN** [comment]
For your questions about,
1. Primary sources : I confirm it is right and the procedure you want is acceptable
2. Status: ex. oiketes. In the book, not oiket. (Termessos), but just oiket.
3. Status: imperial slave, plus don't remove it. My mistake : it needs to be in.

Thanks a lot

**Comment by tuurma** [comment]
@JSBLGPN For the conversion of `diploma` entries: currently they have either `bronze` or `inscription stone` as their source type. Is it okay to just substitute with `diploma`?

Thanks for your replies, all clear now.

**Comment by JSBLGPN** [comment]
Yes. Thanks a lot

**Comment by tuurma** [comment]
updated diploma entries with

```xquery
for $i in collection('/db/apps/lgpn-data/data/persons')//tei:note[.='diploma']/parent::tei:bibl
return 
    (update replace $i/tei:ref/@type with 'diploma',
    update value $i/tei:note[@type="source"] with '')
```

**Comment by tuurma** [comment]
updated all stamp entries with empty subcategory to `Other`

**Comment by tuurma** [comment]
Current state of work on the abbreviations, known problems marked in red

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/449468/59509086-543a3580-8eb0-11e9-9ad8-59c383dc155b.png">

**Comment by tuurma** [comment]
Natural/foster example

<img width="340" alt="image" src="https://user-images.githubusercontent.com/449468/60617581-52d79b00-9dd4-11e9-8f90-332e930cddd9.png">

Foster only example

<img width="653" alt="image" src="https://user-images.githubusercontent.com/449468/60617795-c7123e80-9dd4-11e9-8628-dc0745e49dd4.png">

@JSBLGPN Do I understand correctly that in the second example the entry in blue should not be present in the book since it is not son/daughter nor mother/father relationship?

**Comment by JSBLGPN** [comment]
Papias 8 and Papias 9 are the same individual, and foster will be changed, so there won't be any foster anymore.

Yes, the permitted formulae are 
f. / m./ s./ d. 
f. (ad) / m. (ad.) / s. (ad.) / d. (ad.)
f. (nat.) / m. (nat.) / s. (nat.) / d. (nat.)

**Comment by tuurma** [comment]
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/449468/63178066-91a27700-c049-11e9-9e1f-867394fba186.png">
