### ISSUE TITLE
[book] date handling

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#245]
* [x] ? before all dates 
* [x] with the exception of arch., class., hell., imp., byz.
* [x] No space between ? and the dates. 
* [x] But space between f(irst), m(idle), l(ate) abbreviation and the century. Ex. f. vii ad

Precision:

* [x] C80AD = c. 80 ad
* [x] B80AD = b. 80 ad
* [x] A80AD = a. 80 ad
or = 311 or 315 ad

*import: is it possible to have a list of entries with *import? So either we automate the changes or we do it manually. I have already changed a lot of them.

**Comment by tuurma** [comment]
There are 2660 items, so too much to change manually. I had a look about automated change, could approach it this way:

* [x] if dates notBefore and notAfter are equal then precision EXACT
* [x] if dates notBefore and notAfter correspond with a period on the list then precision PERIOD
* ~~if notBefore and notAfter only differ by 1 year then precision OR~~
* [x] if only notBefore is present then precision AFTER
* [x] if only notAfter is present then precision BEFORE

this already covers many cases. I have also a list of common cases which should be probably translated into periods

 * 100 : 600 >> ii-vi AD
 * 200 : 500 >> iii-v AD
 * 200 : 600 >> iii-vi AD
 * 100 : 150  >> f.ii AD
 * 200 : 250 >> f.iii AD

Not sure about these, probably are named periods too

* -300 : 300 iii BC-iii AD
* [x] 311 : 999 should it be byz? we have defined byz as 311 to 699

**Comment by tuurma** [comment]
```xquery
xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare namespace output="http://www.w3.org/2010/xslt-xquery-serialization";
declare option output:method "html5";
declare option output:media-type "text/html";
<ul>
    {
for $b in collection('/db/apps/lgpn-data/data/persons')//tei:birth[@precision="import"]
        
let $period := doc('/db/apps/lgpn-data/data/resources/xml/datingPeriodDisplay.xml')//tei:date[@from=$b/@notBefore][@to=$b/@notAfter]
let $nb := $b/@notBefore
let $na := $b/@notAfter

order by $b/@notBefore


return 
    <li>
        {$nb/string() || ' : '|| $na/string()}
        {
            if ($period) then 
                ' >> PERIOD ' || $period/string() 
            else if ($nb = $na) then 
                ' >> EXACT ' || $nb/string()
            else ' something else'}
    </li>
}
</ul>

```

**Comment by tuurma** [comment]
@jsblgpn would you be able to confirm my procedure sketched in the comment above and have a quick look at http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/personsWithImportDate.xq ?

These are the cases which don't fall into any of the categories above. I think that ones that use / in dates should be manually edited to avoid it, eg 389/90 : 449/50. Others I could still convert automatically, just need to know if there is a period given like 386 : 424, should that be translated to C or other?

**Comment by tuurma** [comment]
Also prepared a listing of all periods we have defined so far, there's been a mistake reported by Richard (now fixed). Rest looks good but in case I missed something or we should extend that list http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/dateperiods.xq

**Comment by JSBLGPN** [comment]
I agree to automate dates as described above with the exception of this: "if notBefore and notAfter only differ by 1 year then precision OR", this should be done manually.
 
In the list of dates (http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/modules/tools/personsWithImportDate.xq):
1. 311-999 can automatically change into "byz.";
2. I will do some changes manually now in order to cut down the list;
3. Once I have done that I will ask if you could produce a new list for Richard and Michael to have a look at the remaining dates and change theirs manually.

Thanks a lot

**Comment by JSBLGPN** [comment]
I checked the list and changed many. Is it possible for you to produce an updated list, so R and M can check the rest?
Thanks a lot

**Comment by tuurma** [comment]
There are 348 entries remaining on the list after I've run my script. In particular entries where dates contain `/` should be edited, notBefore and notAfter should always be a single number

**Comment by tuurma** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/449468/62492952-28606f80-b7d0-11e9-835d-f2a06fec6b48.png">

**Comment by JSBLGPN** [comment]
I am going through the list once more time, because there are entries with *import that were not in the first version of the list.

**Comment by JSBLGPN** [comment]
I checked it again.
1. Is it possible to change automatically all 567:568 and 569:570 of the list into "exact"?
2. Produce an updated version of the list?
Thanks

**Comment by tuurma** [comment]
Done. The list is always generated on request. New entries showed up for you before because in the first version I was hiding the dates differing by 1 year which I considered candidates for OR. Now it should only get shorter as you edit remaining entries manually.

**Comment by JSBLGPN** [comment]
Thanks a lot! Michael and Richard will do the rest. Hopefully today or tomorrow...

**Comment by JSBLGPN** [comment]
All done on our part. You might like to check if there is any left. 
Thanks

**Comment by tuurma** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/449468/62706508-fa597600-b9ef-11e9-841b-e47e277aad8e.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/449468/62706632-3e4c7b00-b9f0-11e9-8c71-d3c2a64f5d30.png">
