### ISSUE TITLE
reference display

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#248]
Newly authorised book does not show, only page numbers show.

![InkedREFERENCE_LI](https://user-images.githubusercontent.com/18262359/60652171-95828d00-9e3f-11e9-844f-f9862c898fa0.jpg)

**Comment by tuurma** [comment]
Meanwhile has been fixed <img width="1492" alt="image" src="https://user-images.githubusercontent.com/449468/62241334-4184ad00-b3d9-11e9-9b0c-67f62c114f69.png">
