### ISSUE TITLE
Old records missing "period" field

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#249]
E.g. 
![image](https://user-images.githubusercontent.com/20699164/61868789-14646600-aed2-11e9-8cdb-b2ae7d5bddde.png)

**Comment by tuurma** [comment]
There were 354 entries like this, now all fixed

**Comment by tuurma** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/449468/62240972-793f2500-b3d8-11e9-9a89-2a7c5b3c1d21.png">

<img width="985" alt="image" src="https://user-images.githubusercontent.com/449468/62240993-83612380-b3d8-11e9-9c8b-9ad783e7db82.png">
