### ISSUE TITLE
[book] treatment of <> in bibl. details

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#252]
@jsblgpn What is the intended treatment of `<>`? Was it supposed to be superscript or something like this? Sorry, I have a feeling we discussed it but forgot...

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/449468/62713118-7ce83280-b9fc-11e9-847e-daedf89531b4.png">

**Comment by tuurma** [comment]
Currently leads to weird pdf output

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/449468/62713390-f2ec9980-b9fc-11e9-903a-fca79a52e3b9.png">

**Comment by JSBLGPN** [comment]
Yes it is superscript to indicate later edition.

**Comment by tuurma** [comment]
Would it be okay if we changed the superscript marker to `^`? Eg. `II^2`? I can convert existing entries automatically. It would be more in line with e.g. italicised text marker `+` and conveniently identical to TeX convention.

**Comment by tuurma** [comment]
For the moment I assumed we can switch to `^` and after quite a lot of fiddling still I arrived at this

<img width="994" alt="image" src="https://user-images.githubusercontent.com/449468/62724534-83ce6f80-ba13-11e9-8017-db8cc549c9cc.png">

**Comment by tuurma** [comment]
Sorry, only now noticed the whitespace problem, now fixed

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/449468/62724906-4c13f780-ba14-11e9-9c1f-107ca9469701.png">

**Comment by JSBLGPN** [comment]
The superscript 2 is too big. I think the font is not right or the size. Can we change that?
Thanks

**Comment by tuurma** [comment]
@JSBLGPN Will try to fix the superscript. Meanwhile is it okay to switch from `<>` to `^` as superscript marker? I can just run the script to update all existing entries.

**Comment by JSBLGPN** [comment]
Yes that is fine. Thanks

**Comment by tuurma** [comment]
Are the orange ones looking ok? Used previous superscript macro. Red shows the default latex handling.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/449468/62871937-b2529000-bd1c-11e9-8b1d-bece225fd55a.png">

**Comment by JSBLGPN** [comment]
It is too high. For IG II^2^ the superscript 2 should not be higher than IG. For CIJ, no italics for superscripts and no higher than "CIJ".
Thanks a lot

**Comment by tuurma** [comment]
Like this?

<img width="998" alt="image" src="https://user-images.githubusercontent.com/449468/62888548-cf4c8a80-bd3f-11e9-8909-f8e17ed60c1e.png">

**Comment by JSBLGPN** [comment]
It looks good. Below is the picture with in circle what will need changed (just in case).
Thanks a lot
 
![Inkedsuperscript_LI](https://user-images.githubusercontent.com/18262359/62929514-8bdf3400-bdb2-11e9-8b43-82ff798ce663.jpg)

**Comment by tuurma** [comment]
Here are Unicode problems extracted from the sample (still struggling with having both proper Unicode handling and LGPN styling at the same time)

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/449468/62931548-db2b6180-bdbe-11e9-87c2-e2d20ee624ff.png">

**Comment by JSBLGPN** [comment]
Thanks for that. I understand...IBeth She'arim and Phénicie will also need to be italicized.

**Comment by tuurma** [comment]
Extracting this sample into separate issue and will close this one
