### ISSUE TITLE
[book] Dionisia sample

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#253]
Problems reported in this small sample by @jsblgpn:

* [x] Unicode handling (blue)
* [x] dates (pink)
* [x] relationships (yellow)
* [x] references (green)

![Inkedsuperscript_LI](https://user-images.githubusercontent.com/18262359/62929514-8bdf3400-bdb2-11e9-8b43-82ff798ce663.jpg)

**Comment by tuurma** [comment]
Unicode handling

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/449468/62931856-54c34f80-bdbf-11e9-9657-df2ff3cc4443.png">

**Comment by tuurma** [comment]
References

* [ ] small caps and old style numbers
* [x] italics

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/449468/62932272-22662200-bdc0-11e9-835b-03b792f27c70.png">

**Comment by tuurma** [comment]
Dates

@jsblgpn should dates be presented as `128-127 BC` or `165 BC` instead of using minus sign?

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/449468/62932388-4cb7df80-bdc0-11e9-9e23-cfd6415163ac.png">

**Comment by tuurma** [comment]
Relations

@jsblgpn is your marker about the unnecessary space in entry (6), or should the 'wife of' not be present?

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/449468/62932540-9dc7d380-bdc0-11e9-8bee-233b0c2fe0c5.png">

**Comment by JSBLGPN** [comment]
- yes we use BC not minus sign
- wives should not be in: only b. s. f. m.

**Comment by tuurma** [comment]
Thanks!

**Comment by JSBLGPN** [comment]
A few more things:
For Dionysia (2): mosaic should not appear twice in this entry, so we should have (CBCMPIPT 49). In the primary sources, when a reference has the linking element "=", the element "source" should not be repeated.

For Dionysia (12): in the final brackets, the abbreviation for mother (m.) should not be repeated, so we should have "m. Φιλο-, Κλεοπάτρα". There is no alphabetical or gender order in these cases. Relationships are repeated only with the use of relationship types [natural, foster, adoptive]: so "s. (ad), s., f. (nat.), f. (ad.) etc.)". The only order that matters is that son comes before father and daughter before mother. Adoptive parents can come before or after natural parents.
Thanks a lot

**Comment by tuurma** [comment]
References

italicized parts need to be marked in the entry, my copy of data didn't have it done for IBeth Shearim, also updated the Renan, Phenicie on the server

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/449468/62941047-631c6600-bdd5-11e9-82a9-a5dcfb0f84c2.png">

**Comment by JSBLGPN** [comment]
For IMnBeyrouth, it is italicised (though not in the ID box), but still show wrong. Shall we add + in the ID box?

![Annotation 2019-08-13 135127](https://user-images.githubusercontent.com/18262359/62943134-ae347a00-bdd1-11e9-8182-cbba5a54a8d7.png)

**Comment by tuurma** [comment]
improved dates 

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/449468/62943849-ab3e8700-bddb-11e9-93a5-528245004032.png">

and some more date examples

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/449468/62945962-10947700-bde0-11e9-982c-a1eb7e9f49bf.png">

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/449468/62946072-52252200-bde0-11e9-8224-7362c74962b9.png">

**Comment by tuurma** [comment]
@jsblgpn I have my local copy of data, must be out of date, because my version doesn't show the + for IMn Beyrouth, will update my local copy, so as not to lead to confusion

**Comment by JSBLGPN** [comment]
Date examples are correct. Thanks.

**Comment by tuurma** [comment]
Almost done with the relationships, it proved to be much more fiddly than expected. Still incorrect order though, in (12) should be daughter first, then mother. Have to finish for today unfortunately, will continue tomorrow afternoon.

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/449468/62960963-18faab00-bdfc-11e9-8200-94dbadc2612f.png">

**Comment by JSBLGPN** [comment]
No. 3: in final brackets ":" before Jew should go. 
No. 6: highlighted ";" is correct.
No. 12: the order was originally correct (see sample above).

**Comment by tuurma** [comment]
Thanks, that's solved now

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/449468/63029301-967ff300-beb0-11e9-8a71-1eaa6ef4f95c.png">

**Comment by tuurma** [comment]
Fixed repeated source type in = bibl. entries. IGLS volume numbers likely need some tidying up (1) `IGLS XIV (I)` vs (14) `IGLS III.1`. Details of handling small caps in references are specified in #243 though, so I will tick the 'References' item here.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/449468/63060815-9c4af800-bef3-11e9-930d-8b6b33fef254.png">

**Comment by JSBLGPN** [comment]
For IGLS volumes, when we authorised individual volumes, we mistakenly moved away from old practice. IGLS should have been authorised as IG volumes. So just one authorised reference for all volumes and fascicles; that is to say "IGLS". Volumes, fascicles and inscriptions numbers should all have gone to the reference details box. Is there a way to automate this kind of change without taking a lot of your time? Or can you suggest an alternative solution? Certainly fascicle numbers ("subvolumes") should be in round brackets.  
Thanks

**Comment by tuurma** [comment]
@JSBLGPN Okay, I will prepare the conversion list for you to check and will automate the task after OK from you.

**Comment by tuurma** [comment]
Bit of progress on Unicode, more to come

<img width="768" alt="image" src="https://user-images.githubusercontent.com/449468/63091012-57f44200-bf5d-11e9-8360-b1686e9f65d9.png">

**Comment by tuurma** [comment]
Think we are getting very close with Unicode handling, just need to set it up on the server and prepare documentation

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/449468/63172087-2a7ec580-c03d-11e9-8de9-d794e4779a18.png">

**Comment by JSBLGPN** [comment]
Super.
No. 2: can we delete the second mention of mosaic as requested above?
Thanks a lot

**Comment by tuurma** [comment]
Yeah, sure. Grzegorz (the TeX expert helping me on this) just had old (yesterday's) input sample.

**Comment by tuurma** [comment]
Last version of Dionisia, closing this issue. I will create a larger sample for further proofing but still waiting till some missing characters are added to our fonts.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/449468/63847610-6e06f700-c98e-11e9-9246-a406b2c5e5e4.png">
