### ISSUE TITLE
[book] [proofs] alphabetization

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#257]
In the screenshot below, from the "proofing" tab, the alphabetization is incorrect. Two factors to be considered: 

1) Initial letters with diacritical marks, Ἀ, Ἁ, Ἄ, Ῥ, etc., must not come at the end but rather the diacritics should be "ignored" for alphabetization purposes, e.g. Ιεραιος Ἱέριος Ιεροβωλης not Ιεραιος Ιεροβωλης ... Ἱέριος.

2) What are the 2,838 entries at the very beginning showing no initial letter? I cannot seem to find anything to click on to display them, to check what may have gone wrong.

![image](https://user-images.githubusercontent.com/20699164/65868983-53e77c80-e371-11e9-84de-3fe4b1ee2b4b.png)

**Comment by michaelzellmann** [comment]
Further to last, within the entries for the same initial letter there are similar (but inverse?) issues, e.g. not Γάλβας ... Γαακης ... Γαλάτης but Γαακης ... Γαλάτης ... Γάλβας

**Comment by tuurma** [comment]
Understand, thanks, will work on the ordering.

**Comment by tuurma** [comment]
First step to correct alphabetization (still work in progress and I will test it more before deploying on the server)

![image](https://user-images.githubusercontent.com/449468/68120378-7850ee80-ff05-11e9-8b19-b5dafda9c986.png)

**Comment by tuurma** [comment]
[Γα-4.pdf](https://github.com/eXistSolutions/LGPN/files/3803980/-4.pdf)

**Comment by tuurma** [comment]
Current:

![image](https://user-images.githubusercontent.com/449468/68129934-c3c1c780-ff1a-11e9-9229-71120f0763d0.png)

Before:

![image](https://user-images.githubusercontent.com/449468/68130012-e9e76780-ff1a-11e9-8763-a5c04d5c3209.png)

**Comment by tuurma** [comment]
> What are the 2,838 entries at the very beginning showing no initial letter? I cannot seem to find anything to click on to display them, to check what may have gone wrong.

It was due to Roman name entries showing up, now filtered out since they should not be taken into account here.

**Comment by tuurma** [comment]
@michaelzellmann when you have some spare time could you please confirm if the ordering of name headings is now correct and close this issue if so? Attaching today's version of Γ

[Γ (3).pdf](https://github.com/eXistSolutions/LGPN/files/4530157/3.pdf)
