### ISSUE TITLE
[book] [proofs] preliminary results

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#258]
Here as a series of comments within one issue:

## 1. (already in  #255)
=? relationships (where two people may be identical) do not yet appear, to judge e.g. from the entries for Ἰωάννης where at least the entries P5530f4a0-6205-45ef-8461-a79ea660f273 and Pabfbcf66-f2a5-4dd6-b379-e1fc568e8ae0 should have this relation: at the end of both of their entries should come ?= then the serial number of the homonym in parentheses but not bold before the final ;  as in the example attached, see nos. 95 and 111

![image1](https://user-images.githubusercontent.com/20699164/65884997-bcdeec80-e391-11e9-9680-abc83736bd0c.JPG)

**Comment by michaelzellmann** [comment]
## 2. (already in #247)
References repeated in one or more directly following entries need to be abbreviated with ib. Perhaps you are already aware of this; I have marked a few examples in the attached PDF (see no. 3 and following) and one special case where "l." has to be introduced, please let me know if anything is unclear.

The general principle is: Repeated references should be reduced as e.g. when Source is the same and Volume Number is the same, IGLS VI 2767, 12; IGLS VI 2768, 5 should be reduced to IGLS VI 2767, 12; 2768, 5; the same applies where volume number changes, e.g. SEG XXX 1234; SEG XXXIV 1456 should be SEG XXX 1234; XXXIV 1456. Likewise, where same reference is used for different entries, without any intervening change of reference, ib. should be used (e.g. Gamma p. 2 Gessios 9-18)

**Comment by michaelzellmann** [comment]
### 3 and following (extracted into #278)

It seems easiest to note the rest by annotating the PDF directly, as attached,
[Γ_MZR.pdf](https://github.com/eXistSolutions/LGPN/files/3671668/_MZR.pdf)
 but please let me know if this is not useful to you.

**Comment by michaelzellmann** [comment]
## 4. (extracted into #266)

One more character that seems not to render is U+02BE (modifier letter right half ring) in final bracket

**Comment by michaelzellmann** [comment]
## 5. (fixed)

> In at least one entry, an extra number has been wrongly produced: for Γαδωνας there should only be two:
![image](https://user-images.githubusercontent.com/20699164/65974909-ae620500-e465-11e9-8cc6-0c08f69d8a50.png)

> But it looks as though the second has been split into two for some reason:

![image](https://user-images.githubusercontent.com/20699164/65975101-0993f780-e466-11e9-8e3d-20a24b643e0d.png)

> Note also that (3) has somehow wrongly been assigned to a different region than (2) -- but in any case (3) should not exist in the first place.

Now fixed

![image](https://user-images.githubusercontent.com/449468/72423219-2e497c00-3784-11ea-87ad-39b22296d7e9.png)

**Comment by michaelzellmann** [comment]
## 6. (extracted into #272 and #273)

> Based on the next two pages of Γ I add three comments in the PDF with global implications: two concerning abbreviations and one concerning the handling of primary sources when "linked" with =
[Γ_MZR_2.pdf](https://github.com/eXistSolutions/LGPN/files/3677179/_MZR_2.pdf)

**Comment by michaelzellmann** [comment]
## 7. (extracted and fixed in #246)

> ? is missing from headings of names. When in [names] [nym] the [certainty] field is set to ?, the ? needs to appear in the heading: e.g. the record http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pea23be5b-df63-4179-b24e-f0a82379e1dc

> Here is how it should appear in the book (headings 2nd and 3rd from bottom):
![image1(1)](https://user-images.githubusercontent.com/20699164/66044819-4d483900-e51a-11e9-83a7-2085cdee8f2e.JPG)

**Comment by michaelzellmann** [comment]
## 8. (added to #269)

> For chronological ordering of entries, when date is a period, period without query should precede period with query, e.g. (1) imp. ... (2) imp.? (but still (1) imp.? ... (2) byz.)

**Comment by michaelzellmann** [comment]
## 9. (extracted #271)

Running headings at top of page should be: at left, first head-word in bold on page; at right, last head word in bold on page. So, e.g. for pages 5-6 of Γ in the attached, for p. 5 the heading at left should be Γαλλικός not Γαλογας, and the heading at right should be Γασερος not Γασος;
 and for p. 6 the heading at left should be Γασος (the heading at right is correct).

[Γ.pdf](https://github.com/eXistSolutions/LGPN/files/3684742/default.pdf)

**Comment by michaelzellmann** [comment]
## 10. (extracted into #263, fixed)

> Alphabetization of place names: analogously to the headings, special characters need to be treated the same as normal ones, e.g. for D and Ḏ in this case:

![image](https://user-images.githubusercontent.com/20699164/66203601-a8a43380-e6a0-11e9-8e9f-3818cdbeb5e5.png)

> Similarly when there is ‘ or ’ at the beginning of a place name, it should be ignored for alphabetization purposes, and the alphabetization should proceed via the second character, e.g. ‘Araba before Azana (a made-up example)

---

![image](https://user-images.githubusercontent.com/449468/72431483-3d84f580-3795-11ea-9295-dcccaba68b5e.png)

**Comment by michaelzellmann** [comment]
11. (extracted into #266)

> Another character that fails to render: Unicode U+E1B0 (UTF-8 EE 86 B0)

![image](https://user-images.githubusercontent.com/20699164/66210181-1e180000-e6b1-11e9-8f30-f4a8e0492742.png)

**Comment by michaelzellmann** [comment]
## 12. (fixed)

> Period date has failed to render here (P51e42a66-1d52-4338-bee7-bb82d6c313a9): should be in this case ii/iii AD

![image](https://user-images.githubusercontent.com/20699164/66306721-4cd4e700-e8fa-11e9-99cb-6eba38b2d58d.png)

![image](https://user-images.githubusercontent.com/449468/72427775-c64b6380-378c-11ea-9373-57c5cd02b0bd.png)

**Comment by michaelzellmann** [comment]
## 13. (fixed)

> The [details] field in [Secondary source] and [Ref. details] field in [Primary source] will need to be able to render Greek text; currently this is showing up as X's, e.g.

![image](https://user-images.githubusercontent.com/20699164/66308166-48aac880-e8fe-11e9-9796-4162b42217a9.png)

---

![image](https://user-images.githubusercontent.com/449468/72422251-5e901b00-3782-11ea-885c-94eafbed9181.png)

**Comment by michaelzellmann** [comment]
## 14. (extracted into #270)

> Equalise base of all three columns on page as here:

![image](https://user-images.githubusercontent.com/20699164/66556327-ea712600-eb47-11e9-93cc-443f30a46881.png)

> Try to avoid unevenness as here (far left column shorter than the rest):

![image](https://user-images.githubusercontent.com/20699164/66556395-0bd21200-eb48-11e9-8e07-0532a0f97460.png)

**Comment by michaelzellmann** [comment]
## 15. (extracted into #268)

> The character ώ is showing up differently in headings: it should not be italic (as marked in red) but rather have the same bold face as the version of the same character ω marked in green:

![image](https://user-images.githubusercontent.com/20699164/66556634-8b5fe100-eb48-11e9-91e7-900df0f810eb.png)

> Here is how it should appear, from a previous volume:

![IMG_2500](https://user-images.githubusercontent.com/20699164/66629949-17324580-ebfb-11e9-9a50-90c0f5ae2fe7.JPG)

**Comment by michaelzellmann** [comment]
## 16. (extracted to #267)

> Greek italic vowels (alpha, epsilon, eta, omicron, upsilon,  omega but not iota) with oxytone accent (i.e. ά, έ, ή, ύ, ώ) are slighter larger than other letters; they should be the same size

**Comment by michaelzellmann** [comment]
## 17. (fixed)

> The character combining underdot ( ̣) is not rendering well with capital letters in Latin alphabet, e.g. in P82b0f700-40de-4699-93a9-ae67442941e4

![image](https://user-images.githubusercontent.com/20699164/66557257-7afc3600-eb49-11e9-8fb8-aee8dd870916.png)

> The dot should be centered under the G not to the right of it: G̣

---

Now fixed

![image](https://user-images.githubusercontent.com/449468/72421649-2e944800-3781-11ea-95b2-0ed8f36ce1eb.png)

**Comment by michaelzellmann** [comment]
## 18. (extracted into #269)

> Sorting by date is incorrect. See e.g. Gamma p. 9 Germanos 121-149. According to LGPN rules in this sequence, those dated imp. should come first (148-9), followed by i-ii AD (121), ii-iii AD (146-7), f. iii AD (145), ?201 AD (122), 202 AD (123), c. 202-215 AD (130), 203 AD (124), 205 AD (125), c. 207-220 AD (136), ?208 AD (126), 214 AD (128-9), ?214 AD (127), 215 AD (131-2), 216 AD (133-4), 219 AD (135), c.223-225 AD (138), ?223 AD (137), 236 AD (139), 239 AD (140), c. 240-1 AD (141-3) , ? 242 AD (144).

![image](https://user-images.githubusercontent.com/20699164/66557506-e5ad7180-eb49-11e9-9e5a-c631e89829a7.png)

> The principle is that anyone who could (even if improbably) be dated as early as 31 BC (when the Imperial period conventionally begins) should come before anyone who has a period date or precise date later than that. Likewise anyone dated ii-iii AD has to come before someone dated 201 AD. The same rule applies throughout.

**Comment by michaelzellmann** [comment]
## 19. (fixed)

> Secondary refs. do not function correctly. Volume numbers are always large caps. when they should be small (e.g. PLRE III, SEG L). For some reason RE is never italicised. 

![image](https://user-images.githubusercontent.com/449468/72424533-75d10780-3786-11ea-8385-9e3d82165e27.png)
--- 

![image](https://user-images.githubusercontent.com/449468/72425270-bed58b80-3787-11ea-8ed9-208a2eb3bb0c.png)

**Comment by michaelzellmann** [comment]
## 20. (fixed)

> biling. and triling. should be bracketed: (biling.) and (triling.)

![image](https://user-images.githubusercontent.com/449468/72423525-b7f94980-3784-11ea-89a8-af7107f1fec2.png)

---

![image](https://user-images.githubusercontent.com/449468/72424025-99e01900-3785-11ea-86fa-934381413d24.png)

**Comment by michaelzellmann** [comment]
## 21. (fixed)

NB that correct display of generation numbers requires updating Generation index in Admin menu (should be definitely done before final proofs are generated) 
![image](https://user-images.githubusercontent.com/449468/72431186-82f4f300-3794-11ea-8945-95d1f91e764f.png)


![image](https://user-images.githubusercontent.com/449468/72431089-475a2900-3794-11ea-92b6-097139944928.png)


---
> When a parent and a child have the same name, this needs to be reflected in the final bracket and in their relationship in the final bracket. The parent is designated [name] I and the child [name] II. E.g. [name] (II s. [name] I) for the son and [name] (I f. [name] II) for the father.

> So here we have the name Γάϊος for both a father and one son among several children:

![image](https://user-images.githubusercontent.com/20699164/66558723-f3fc8d00-eb4b-11e9-9621-0ad826713142.png)


> The father, who needs to be referred to as I, in the final bracket as (I f. Γάϊος II), is P7f96f2d9-a2a6-488c-907f-ca4dbb352409 ; the son, who needs to be II, final bracket (II s. Γάϊος I) is Paf47f71f-a2f3-4896-b135-91bfdee4b328

> So for the son his final bracket should be (II s. Γάϊος I) and for the father (I ... f. Ἀντίοχος, ... Πετρώνιος, Γάϊος II, Θηδιων ...)

> Here is an example from a printed volume for comparison, where there are three generations (I, II, III) in nos. 40-41 and 43-45
![IMG_2501](https://user-images.githubusercontent.com/20699164/66629896-f4079600-ebfa-11e9-8fed-3d7ae4166840.JPG)

**Comment by tuurma** [comment]
I've either fixed (in such cases pasted screenshots directly into Michael's comments above) or extracted into separate issues, so closing this one as it got very long.
