### ISSUE TITLE
[Input form] [General] [Volume]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#260]
To the pull-down list please add two items: V7a, V7b

**Comment by tuurma** [comment]
Would you like them to be arranged in more natural order, or V7 closer to the top like below?

![image](https://user-images.githubusercontent.com/449468/66919288-590b2380-f021-11e9-8f2e-04a606e5592a.png)

**Comment by michaelzellmann** [comment]
Natural order for now, please. Many thanks. This will also mean anything imported for the trial Trismegistos export should go in as 7a.

On Oct 16, 2019, at 1:30 PM, Magdalena Turska <notifications@github.com<mailto:notifications@github.com>> wrote:


Would you like them to be arranged in more natural order, or V7 closer to the top like below?

[image]<https://user-images.githubusercontent.com/449468/66919288-590b2380-f021-11e9-8f2e-04a606e5592a.png>

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/66925439-a771ef80-f02c-11e9-9b2d-7100078e0bd6.png)

**Comment by michaelzellmann** [comment]
![image](https://user-images.githubusercontent.com/20699164/66927298-793de100-f027-11e9-80ad-314c377eecc6.png)

When we try to save new entries under V7a we get this error message

**Comment by tuurma** [comment]
Sorry, my mistake. Would you mind trying again? Should work now.

**Comment by michaelzellmann** [comment]
Yes, working fine now, thanks.
________________________________
