### ISSUE TITLE
[book] hyphen-n-dash

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#275]
* [x] place name separator
* [x] in names of unidentified relatives when incomplete

![image](https://user-images.githubusercontent.com/449468/72432951-94d89500-3798-11ea-9707-cc4dcb2bdc39.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/72433158-0adcfc00-3799-11ea-84f7-77f209688a01.png)

**Comment by tuurma** [comment]
@michaelzellmann There are 283 entries where relation name contain hyphen - mostly it would be as double hyphen. What should I do conversion-wise?

Representative cases:
<ul>
 <li>Ισαμ-- (double, final position)</li>
 <li>--αρεος (double, initial position)</li>
 <li>Σαλλου-(single, final position)</li>
<li>ΑΡΑ--ης(double, middle)</li>
 <li>Anu-balassu-iqbi (single, middle)</li>
</ul>

Full list

<ol>
    <h2>283</h2>
    <li>Ισαμ--</li>
    <li>Μαρ--</li>
    <li>--εγος</li>
    <li>Θ--η</li>
    <li>Θ--η</li>
    <li>Μαρ--</li>
    <li>Ζη--</li>
    <li>Ζη--</li>
    <li>Μαρ--</li>
    <li>--βος</li>
    <li>Ξεινο--</li>
    <li>--αρεος</li>
    <li>Ἀπολλ--</li>
    <li>Μ--ινεος</li>
    <li>Δο--νις</li>
    <li>Δο--νις</li>
    <li>Ῥομ--</li>
    <li>Ἀπολλον--</li>
    <li>--ουχχας</li>
    <li>Βαρναν--</li>
    <li>Προ--</li>
    <li>Μαρθαν--</li>
    <li>-σιανός</li>
    <li>Σο--</li>
    <li>Σαλλου-</li>
    <li>Μα--</li>
    <li>-αδαλλος</li>
    <li>Βαρ--</li>
    <li>--ωνης</li>
    <li>Σαμβ-</li>
    <li>Σε--</li>
    <li>Ἀλεξαν--</li>
    <li>Βαρσιγαρι--</li>
    <li>ΑΡΑ--ης</li>
    <li>Γορη--</li>
    <li>--λιος</li>
    <li>Si-iš-pi-iš</li>
    <li>Σα--</li>
    <li>Αρο--</li>
    <li>--λισος</li>
    <li>Μευαι--</li>
    <li>--ωερος</li>
    <li>Σ--</li>
    <li>Σ--</li>
    <li>--ΕΣΑ</li>
    <li>Anu-aḫ-ittannu</li>
    <li>Ina-qibit-Anu</li>
    <li>Anu-belšunu</li>
    <li>Anu-aḫ-ittannu</li>
    <li>Anu-balassu-iqbi</li>
    <li>Nidintu-Anu</li>
    <li>Anu-balassu-iqbi</li>
    <li>Nidintu-Anu</li>
    <li>Nidintu-Anu</li>
    <li>Anu-balassu-iqbi</li>
    <li>Ina-qibit-Anu</li>
    <li>Antu-banat alias Ereštu-Nanaya</li>
    <li>Anu-balassu-iqbi</li>
    <li>Nidintu-Anu</li>
    <li>Anu-aḫ-ittannu</li>
    <li>Nidintu-Anu?</li>
    <li>Nanaya-iddin</li>
    <li>Kidin-Anu</li>
    <li>Ayata-Nanaya</li>
    <li>Nanaya-iddin</li>
    <li>Idat-Anu</li>
    <li>Anu-uballiṭ</li>
    <li>Anu-uballiṭ</li>
    <li>Anu-uballiṭ</li>
    <li>Nidintu-Anu</li>
    <li>Anu-bullissu</li>
    <li>Anu-belšunu</li>
    <li>Ina-qibit-Anu</li>
    <li>Kidin-Anu</li>
    <li>Uballissu-Nabu</li>
    <li>Marduk-eriba</li>
    <li>Δια--ος</li>
    <li>--μαδων</li>
    <li>Κυ--</li>
    <li>Τιβ. Κλ. --</li>
    <li>Τιβ. Κλ. --</li>
    <li>Τιβ. Κλ. --</li>
    <li>Τιβ. Κλ. --</li>
    <li>Nidintu-Anu</li>
    <li>Anu-ikṣur</li>
    <li>Anu-ab-uṣur</li>
    <li>---iddin</li>
    <li>Ἡ--φῶν</li>
    <li>Dumqi-Anu</li>
    <li>--ος</li>
    <li>--ης</li>
    <li>Αμμ--</li>
    <li>Σαληκ--</li>
    <li>Αβ--</li>
    <li>Βα--</li>
    <li>--ίς</li>
    <li>---κος</li>
    <li>Να--</li>
    <li>Δαλ--σος</li>
    <li>Σαλ--</li>
    <li>--ννος</li>
    <li>--τος</li>
    <li>Κα--</li>
    <li>Οα--</li>
    <li>Δι--</li>
    <li>--ινας</li>
    <li>Εσ---</li>
    <li>--ιμης</li>
    <li>Ἀντ--</li>
    <li>Σαλλ--</li>
    <li>Αν--</li>
    <li>Συ---</li>
    <li>--νανος</li>
    <li>Ζα---</li>
    <li>--ιγγινος</li>
    <li>--ος</li>
    <li>--εια</li>
    <li>--κιου (gen.)</li>
    <li>--ληλος</li>
    <li>Eruccius Apio--</li>
    <li>--ω̣τος</li>
    <li>--ρίδης</li>
    <li>--ν</li>
    <li>Α--</li>
    <li>-κλῆς</li>
    <li>Šipqat-Ištar</li>
    <li>--μανος</li>
    <li>Μανε--</li>
    <li>[Γ.] Ἰούλιος --εινος</li>
    <li>Τιβ. Κλ. --</li>
    <li>Τιβ. Κλ. --</li>
    <li>-ασέας</li>
    <li>--ωτος</li>
    <li>Ἀθην-</li>
    <li>Κλεα-</li>
    <li>-ων</li>
    <li>-αχος</li>
    <li>-δρος</li>
    <li>Δα--δας</li>
    <li>Γάϊος Ἰούλιος --ιανός</li>
    <li>Απα--</li>
    <li>---βριων</li>
    <li>Δο--</li>
    <li>Σεκουνδ--</li>
    <li>--θεος</li>
    <li>--δης</li>
    <li>Πολλ--</li>
    <li>Ὀλυμπ--</li>
    <li>Δομι--</li>
    <li>--εσιανός</li>
    <li>Anu-belšunu</li>
    <li>Ν--αιος</li>
    <li>--ρμα--</li>
    <li>Αυσ--</li>
    <li>--ρανος</li>
    <li>Κλαυδι--</li>
    <li>Αυ--</li>
    <li>Μαρ--</li>
    <li>Ced--bius</li>
    <li>--βεος</li>
    <li>Σ--</li>
    <li>Αυρ. Σ--ιτη</li>
    <li>--κριτος</li>
    <li>Ζη--</li>
    <li>--δωρος</li>
    <li>Νον--</li>
    <li>--μήδης</li>
    <li>[Ἰούλ.] Αὐρ. --</li>
    <li>Šipqat-Ištar</li>
    <li>Χα--</li>
    <li>--ν</li>
    <li>Μανα--</li>
    <li>---ονη</li>
    <li>--εια</li>
    <li>Φιλο--</li>
    <li>Μολ--</li>
    <li>Φαλ--αγας</li>
    <li>Σ̣αμ---</li>
    <li>Φιλ̣--</li>
    <li>--ος</li>
    <li>Πα--</li>
    <li>Ἀ̣πολ[--]</li>
    <li>Ἀπολ--</li>
    <li>Θ̣ελλ̣---</li>
    <li>Σουσ--</li>
    <li>.νδο--</li>
    <li>Μ--</li>
    <li>Μ--</li>
    <li>--ς</li>
    <li>Γα--ος</li>
    <li>--ρεσία</li>
    <li>---ρος</li>
    <li>Ἑρμοσ--</li>
    <li>Μο--</li>
    <li>--αιας</li>
    <li>-εοτος</li>
    <li>--ανιος</li>
    <li>Α.σιοι--</li>
    <li>Τι--</li>
    <li>Ἀσκλ--</li>
    <li>--ρίδης</li>
    <li>Ἀρτ̣--</li>
    <li>Σωστ--</li>
    <li>Ἀπολλ--</li>
    <li>--ρης</li>
    <li>Τι--</li>
    <li>--φιλος</li>
    <li>--άσων</li>
    <li>--δ̣οτος</li>
    <li>--νις</li>
    <li>--ων</li>
    <li>Νι--</li>
    <li>-μος</li>
    <li>Α--</li>
    <li>Σα--</li>
    <li>Φιλο--</li>
    <li>--τος</li>
    <li>--ω̣τος</li>
    <li>--πις</li>
    <li>Αμ--ος</li>
    <li>--νη</li>
    <li>--θεος</li>
    <li>--αδδος</li>
    <li>Γαλ--</li>
    <li>--ηαθη</li>
    <li>Σαυμο--</li>
    <li>Αυ--τος</li>
    <li>Αυ--τος</li>
    <li>Σ--</li>
    <li>--νος</li>
    <li>Ζο--</li>
    <li>--τα--</li>
    <li>-τ̣ος</li>
    <li>Αβδ--</li>
    <li>-ης</li>
    <li>-ης</li>
    <li>Ἐπιγα--</li>
    <li>--ιμιος</li>
    <li>--όδωρος</li>
    <li>--αρία</li>
    <li>--φιλος</li>
    <li>Ἑρ--</li>
    <li>--ογένης</li>
    <li>--κράτης</li>
    <li>Ἀντ[...]ατη--</li>
    <li>Ἀπο--</li>
    <li>-δωρος</li>
    <li>Μαλχ--</li>
    <li>Εἰρην--</li>
    <li>--ώνιος</li>
    <li>Mar-bit-Nanaya</li>
    <li>Ἡρα--</li>
    <li>Λυσα-</li>
    <li>Ἰσι-</li>
    <li>Νο-</li>
    <li>Μεγα-</li>
    <li>Ἀριστομ-</li>
    <li>-όθεος</li>
    <li>-έων</li>
    <li>Ορο-</li>
    <li>Δια̣-</li>
    <li>Δι-</li>
    <li>--ορος</li>
    <li>Αουα̣δ̣--</li>
    <li>--bwl</li>
    <li>--ln--</li>
    <li>Μα--</li>
    <li>Μι--θ̣ο̣υ̣ (gen.)</li>
    <li>--ρ̣ιος</li>
    <li>--ν̣ου (gen.)</li>
    <li>Α--</li>
    <li>---ων</li>
    <li>--δων</li>
    <li>Ἡρα--</li>
    <li>Μεγιστ--</li>
    <li>Νη--</li>
    <li>Π̣α̣--</li>
    <li>Στρα--</li>
    <li>Δο--</li>
    <li>--ιος</li>
    <li>Εὐνο--</li>
    <li>Μ---</li>
    <li>Κο---</li>
</ol>

**Comment by tuurma** [comment]
Between place names

![image](https://user-images.githubusercontent.com/449468/72446800-7f716400-37b4-11ea-9b56-14d108bf74ce.png)

**Comment by michaelzellmann** [comment]
Thanks, Magdalena, here most cases of single and double dashes are inconsistencies on our part that should be triple dashes (eventually converted to M-dash in the output; while double dash is converted to N-dash), but some single dashes are correct and have to be kept. Could you send me a version of the full list with links to the individual entries, and I will correct those that need correction?

Thanks,

Michael

**Comment by tuurma** [comment]
@michaelzellmann Sure, just added it to the Proofing menu

![image](https://user-images.githubusercontent.com/449468/72448681-b6954480-37b7-11ea-9c2f-66e33ee80b62.png)

**Comment by tuurma** [comment]
Oups, bit premature, links don't work yet...

**Comment by tuurma** [comment]
Now fixed

**Comment by michaelzellmann** [comment]
Many thanks, they should all be resolved now

**Comment by tuurma** [comment]
Freshly generated, looks ok I think

![image](https://user-images.githubusercontent.com/449468/72509698-5dc1bc80-3848-11ea-9bd0-3ef9987cf4e5.png)
