### ISSUE TITLE
[book] gender-based labels

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#277]
![image](https://user-images.githubusercontent.com/449468/72433230-2942f780-3799-11ea-956a-b46afbf3f3a8.png)

**Comment by tuurma** [comment]
test case:

Μαρειη (Jew priest instead of priestess)

![image](https://user-images.githubusercontent.com/449468/72726111-d47ff200-3b87-11ea-8d37-0e45122902b8.png)

```<category xml:id="christian_priest">
            <catDesc xml:lang="en">priest</catDesc>
            <catDesc xml:lang="en" sex="f">priestess</catDesc>
        </category>
```

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/72731405-f67f7180-3b93-11ea-9f27-30e607521cea.png)

**Comment by tuurma** [comment]
@michaelzellmann  

Could you advise me if these are gender variants? If so, what are the full male and female forms (also, if these should be abbreviated for display in the book?)

* threptos/e
* tethremmenos/e/on

**Comment by michaelzellmann** [comment]
Thanks, Magdalena, they are gender variants, male = threptos and tethremmenos; female = threpte and tethremmene; and they should be printed in full, no abbreviations.

On Jan 20, 2020, at 1:50 PM, Magdalena Turska <notifications@github.com<mailto:notifications@github.com>> wrote:


@michaelzellmann<https://github.com/michaelzellmann>

Could you advise me if these are gender variants? If so, what are the full male and female forms (also, if these should be abbreviated for display in the book?)

  *   threptos/e
  *   tethremmenos/e/on

**Comment by tuurma** [comment]
Thanks, added these forms for the future though atm we don't have any female entries for them.
