### ISSUE TITLE
Multiple indications of profession etc. need clearer structure.

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#295]
> RC: Multiple indications of profession, office, religion etc. need clearer structure. Sometimes they are separated by a : (e.g. saint: abbot), sometimes no punctuation (e.g. Jew priest). In previous vols. I am fairly sure that a comma has been used to separate multiple professions/offices (e.g. deacon, presbyt.) and a back-slash for office and religion (e.g. priest/Jew). I need to check. In general, a clear structure for the order of the entire contents of the FB is needed, some of which is our responsibility.

> MT: We have the system in place for Office/Religion/Profession etc where one assigns a main category and then a subcategory, if applicable. Vas for category/subcategory pairs are perhaps not perfectly consistent, e.g. in Religion we have the main category priest with subcategories civic/private/federal and another main category Jew with subcat. presbyter/priest/deacon.... Basic rule for linking category and subcategory is with just a space, no punctuation, so Jew priest and : between multiple entries, so potentially Jew priest: archon (sorry, idiotic example).
> MT: I'm happy to streamline this, but we'd need a revised category/subcategory system (and convert the entries which thus require changes).

> RC: I have checked in the published volumes, and find that all multiple professions, statuses, etc. are punctuated with a backslash - so Jew/presbyt. martyr/saint and so on.

_Originally posted by @RichardLGPN in https://github.com/eXistSolutions/LGPN/issues/292#issuecomment-761164390_

**Comment by tuurma** [comment]
Changed the algorithm to use '/' as a separator throughout. Rendition now seems mostly okay, but some cases still look rather weird, e.g. Σαμουῆλος (23), http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-editor/editor.xhtml?id=Pff4be8ec-0088-4726-8de6-b98b4de3f5a0 bottom example

![image](https://user-images.githubusercontent.com/449468/106490524-3622ae00-64b6-11eb-8b52-ee22cacb512c.png)

![image](https://user-images.githubusercontent.com/449468/106490744-6c602d80-64b6-11eb-8e19-572f0be23ded.png)

@RichardLGPN

**Comment by RichardLGPN** [comment]
Yes, Jew/presbyt./Jew/deacon won't do. It has to reduce to Jew/presbyt./deacon.
________________________________

**Comment by tuurma** [comment]
Ok, thanks, I'll work on the grouping.

**Comment by tuurma** [comment]
Reviewing the list of status entries which are to be printed, the only need for grouping should arise with subtypes of Jew ish religious positions and subtypes of slaves.

I have doubts about 'slave/freed.' status, perhaps it would be better to register a person with 2 separate statuses: 'slave' and 'freed' but this should not lead to any issues for the book, as the output would look the same anyway.

[statusList.pdf](https://github.com/eXistSolutions/LGPN/files/6597154/statusList.pdf)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/120785586-8d509200-c52d-11eb-8eac-518fa384929f.png)

**Comment by RichardLGPN** [comment]
slave/freed. must remain. It refers to people at the moment of emancipation and has been widely used in previous volumes.

Richard
________________________________
