### ISSUE TITLE
[name] final bracket

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#64]
Widen the box (full page width if possible) to make it easier to enter and edit longer text strings

**Comment by tuurma** [comment]
attempted but difficult to find my way in the bootstrap/betterform maze of stylesheets
I hope @plutonik-a will come with a new proposal for styling, getting rid of bootstrap altogether

**Comment by tuurma** [comment]
fixed with @plutonik-a's layout changes, closing
