### ISSUE TITLE
[name] language selection

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#66]
Second line of [name] area, box with language/ethnicity selections, add an option "Lallnamen"

**Comment by tuurma** [comment]
![image](https://cloud.githubusercontent.com/assets/449468/26104275/02a6c408-3a35-11e7-86f4-026b339687cb.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27182753-3bf9be48-51d4-11e7-8e30-f826661e096b.png)
