### ISSUE TITLE
[search]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#67]
Search function does not return correct results, e.g. Γεννάδιος should have at least 3 results and currently returns none

**Comment by tuurma** [comment]
searching for places such as Tyre returns no results
also Στράτων	from Berytos-Beirut is not being found when searching by name

**Comment by tuurma** [comment]
![image](https://cloud.githubusercontent.com/assets/449468/26455567/8a291a3c-4162-11e7-86f8-5c557aafb63c.png)

**Comment by tuurma** [comment]
search for Κερδων returns 7 entries (6 of which show the name Κέρδων) while searching directly for Κέρδων only returns 1

similarly Αμμωνιοσ - 20 (all showing Ἀμμώνιος) but directly for Ἀμμώνιος - 3

might be Unicode normalization or whitespace issue

**Comment by JSBLGPN** [comment]
search for references is not working...example, SEG, IG, etc...

**Comment by tuurma** [comment]
Κοσμᾶς
Δαμέας
Ἡρωΐδης
