### ISSUE TITLE
[primary sources] add 'textual annotations` field

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#69]
Add text box at the far right of line 1, "textual annotations" - make the box as wide as possible.

**Comment by tuurma** [comment]
adjust the structure

```xquery
for $i in collection('/db/apps/lgpn-data/data/persons')//tei:bibl[@type='primary'][not(tei:note)]

return 
    update insert <note xmlns="http://www.tei-c.org/ns/1.0"/> into $i
```

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/28118880-c991162a-670a-11e7-8d56-e77c088ee79b.png)
