### ISSUE TITLE
Redesign editor form (editor.xhtml)

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/LGPN#73]

**Comment by tuurma** [comment]
ideas

[ ] condense the inputs, make them smaller and closer together
[ ] move + and delete buttons so they don't occupy as much space
[ ] visually distinguish main sections: general, names, primary/secondary sources, places, status, relationships
[ ] visually distinguish the repeatable entries inside sections (eg `attested form` inside `Name` in `Names` main section)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/LGPN/pull/74

@tuurma  Please have a look at the "name"-form repeat: The replicant should be placed underneath the parent container, but instead opens under attested form. The structure should be updated here.
