### ISSUE TITLE
[Relationships]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#78]
In drop-down list from autocomplete field, order results in order of most recently updated/created

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/28629215-bf557ac4-721e-11e7-8eea-7f8eef54b3c5.png)

![image](https://user-images.githubusercontent.com/449468/28629245-cf07dfc0-721e-11e7-8ea5-d7b873429a82.png)
