### ISSUE TITLE
place sub-form: 

### ISSUE THREAD

**Issue by JSBLGPN** [eXistSolutions/LGPN#79]
The most recent version of the place sub-form is not showing for all the place names. Example Arados, a place authorized with an old version of the place sub-form.

**Comment by JSBLGPN** [comment]
Actually it is also the case for new places when I try to modify them...example Baitokaike.

**Comment by tuurma** [comment]
confirmed, for Arados:

![image](https://user-images.githubusercontent.com/449468/27589504-97d41a60-5b43-11e7-9952-2ac0358b8576.png)
