### ISSUE TITLE
Redesign place subform

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/LGPN#80]
* related #73, #79

**Comment by plutonik-a** [comment]
Markup and styling is completed.  

But two JavaScript bugs remain:
1. On page load, the repeat group "Name Variants" `<xf:repeat ref="instance('i-place-default')/TEI:place/TEI:placeName" id="r-name">`  is repeated three times, instead of only being triggered by the repeat button.
2. The select input (autocomplete functions) isn't initialized properly, so the input rendering fails. The bug already existed in the former code.

![screenshot-place-subform](https://user-images.githubusercontent.com/1157669/26894255-25a18638-4bbe-11e7-9c7c-f05fbaf399fe.png)

<img width="307" alt="bildschirmfoto 2017-06-07 um 20 05 49" src="https://user-images.githubusercontent.com/1157669/26894288-3d0c9b46-4bbe-11e7-937e-bcc045036c29.png">

<img width="1049" alt="bildschirmfoto 2017-06-07 um 19 59 22" src="https://user-images.githubusercontent.com/1157669/26894378-85f395da-4bbe-11e7-9389-ea17823e1887.png">

**Comment by tuurma** [comment]
finally closed with c5698f5ec2a71cec007300db7888524f0d9fa74c
