### ISSUE TITLE
[editor] compact the inputs, applying 2column layout where possible

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#87]

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27081244-634ab630-5037-11e7-8a88-d60e357823bf.png)

**Comment by tuurma** [comment]
@plutonik-a ID fields likely still needs to span full width to accommodate long ids, could you please propose the correct markup/styling for that?

**Comment by plutonik-a** [comment]
Sure, I'll fix this in a new PR.

**Comment by tuurma** [comment]
This looks really nice @plutonik-a, thanks. Please follow up for other sections, leaving only Source, Dating and Final bracket fields at full width.

**Comment by plutonik-a** [comment]
### ≥ 992px

<img width="1040" alt="bildschirmfoto 2017-06-14 um 17 21 47" src="https://user-images.githubusercontent.com/1157669/27140618-4d367dd0-5126-11e7-8635-bcb455707504.png">

---

### > 768px

<img width="808" alt="bildschirmfoto 2017-06-14 um 17 22 14" src="https://user-images.githubusercontent.com/1157669/27140633-550c7870-5126-11e7-8c1a-c6ac2290ad59.png">

---

### ≤ 768px

<img width="310" alt="bildschirmfoto 2017-06-14 um 17 22 35" src="https://user-images.githubusercontent.com/1157669/27140652-5d07d2cc-5126-11e7-9df4-2727798c77bc.png">
