### ISSUE TITLE
[form] remove rarely used sections from default model

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN#91]
Roman names, Status, Profession, Occupation and Religion sections are rarely needed, so they should be only added to the model and form on demand

**Comment by plutonik-a** [comment]
I will assign this issue to myself, because I'm going to fix it with the solution for #100

**Comment by tuurma** [comment]
ok, just remove unnecessary sections from `resources/xml/teiPersonTemplate.xml` once you have #100 fixed

**Comment by tuurma** [comment]
now that #100 is basically fixed, I will just do that and deploy to production
