### ISSUE TITLE
[relationships] [search relative]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#98]
in multiple-line entries in the list of results, the second line overlaps with and is obscured by the following entry

**Comment by plutonik-a** [comment]
@michaelzellmann 
Could you please provide a screenshot and a short description of how to reproduce the bug?

**Comment by tuurma** [comment]
I think this is what Michael was referring to:

![image](https://user-images.githubusercontent.com/449468/27182468-1790f5ea-51d3-11e7-8f8c-0f153eea4106.png)

To reproduce: search for e.g. 'αγα' in Search Relative field

Related issue, when displaying autocomplete proposals for places

![image](https://user-images.githubusercontent.com/449468/27182389-de4de194-51d2-11e7-9ad3-0f114b4e99fa.png)

**Comment by michaelzellmann** [comment]
Yes, exactly, thanks

**Comment by plutonik-a** [comment]
Result of fixed layout bug:

<img width="334" alt="bildschirmfoto 2017-06-16 um 13 50 15" src="https://user-images.githubusercontent.com/1157669/27225532-fb293dcc-529a-11e7-9027-236f81493401.png">
