### ISSUE TITLE
[general] and [primary sources] [certainty] after [date]

### ISSUE THREAD

**Issue by michaelzellmann** [eXistSolutions/LGPN#99]
Add to menu options: "c."

**Comment by tuurma** [comment]
To confirm @michaelzellmann, would you like another option available in 'certainty' dropdown

![image](https://user-images.githubusercontent.com/449468/27177227-7e5fc334-51bd-11e7-8905-bf46e12ae4af.png)

**Comment by michaelzellmann** [comment]
Yes, exactly, thanks

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/27183763-b428f804-51d7-11e7-8d92-19133dfdf756.png)
